### ISSUE TITLE
Content is not sanitized

### ISSUE THREAD

**Issue by krzyk** [yegor256/netbout#1008]
When I post following content in netbout message:

```
public void saveContent(String content) throws IOException {
FileOutputStream stream = new FileOutputStream(file); for (int i = 0, len = content.length(); i < len; i++) { stream.write(content.charAt(i)); } }
}
```

then I will get Internal Application Error with stack trace:

```
java.io.IOException: org.xml.sax.SAXParseException; lineNumber: 76; columnNumber: 119; The content of elements must consist of well-formed character data or markup.
    at org.takes.rs.RsPrettyXML.getDocType(RsPrettyXML.java:206)
    at org.takes.rs.RsPrettyXML.prepareDocType(RsPrettyXML.java:160)
    at org.takes.rs.RsPrettyXML.transform(RsPrettyXML.java:137)
    at org.takes.rs.RsPrettyXML.make(RsPrettyXML.java:104)
    at org.takes.rs.RsPrettyXML.head(RsPrettyXML.java:88)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithCookie.previousValue(RsWithCookie.java:168)
    at org.takes.rs.RsWithCookie.access$100(RsWithCookie.java:63)
    at org.takes.rs.RsWithCookie$1.head(RsWithCookie.java:118)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:115)
    at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
    at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:134)
    at org.takes.rs.RsWithCookie$1.body(RsWithCookie.java:129)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsPrint.printBody(RsPrint.java:159)
    at org.takes.rs.RsPrint.print(RsPrint.java:113)
    at org.takes.http.BkBasic.print(BkBasic.java:99)
    at org.takes.http.BkBasic.accept(BkBasic.java:77)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable$BkThreads.accept(BkTimeable.java:95)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.xml.sax.SAXParseException; lineNumber: 76; columnNumber: 119; The content of elements must consist of well-formed character data or markup.
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:338)
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
    at org.takes.rs.RsPrettyXML.getDocType(RsPrettyXML.java:202)
    ... 33 more
```

When I revisit the same bout I'm still getting this error, please fix it.

**Comment by dmzaytsev** [comment]
@krzyk did you post exactly as written above?

I just posted the same text

![image](https://cloud.githubusercontent.com/assets/9972909/13026843/897b363a-d258-11e5-83f7-6d4da503aae8.png)

**Comment by krzyk** [comment]
@dmzaytsev yes, exactly as in the report, I tried it again and I see this again, another bout is inaccessible.
I wonder, maybe it is a browser thing, I'm using Firefox 46.

**Comment by krzyk** [comment]
@dmzaytsev I added you to the bout (but it says that it couldn't sent email notification to you) and posted the same code and it failed again.

**Comment by dmzaytsev** [comment]
@krzyk hm.. you're right it's a browser related issue
I was be able to open that bout in Chrome
and got the error on the same bout in Firefox

Try to use Chrome as workaround for now

Thanks for the reporting

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@krzyk milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
@krzyk thanks for this report, I added 15 mins to your account, in transaction `77265594`
