### ISSUE TITLE
"incorrect alias" mistake

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#1023]
When I'm trying to invite someone to a bout via RESTful API, I'm getting this answer:

```
incorrect+alias+%22krzyk%22%2C+try+again
```

Everything was fine some time ago, but it's happening now... Would be great to check and reproduce. It's rather urgent.

Full stack trace:

```
com.netbout.spi.Friends$UnknownAliasException: incorrect+alias+%22yegor256%22%2C+try+again/INFO
        at com.netbout.client.RtFriends.invite_aroundBody0(RtFriends.java:93)
        at com.netbout.client.RtFriends$AjcClosure1.run(RtFriends.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
        at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
        at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
        at com.netbout.client.RtFriends.invite(RtFriends.java:78)
        at com.netbout.client.retry.ReFriends.invite_aroundBody0(ReFriends.java:72)
        at com.netbout.client.retry.ReFriends$AjcClosure1.run(ReFriends.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
        at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
        at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
        at com.netbout.client.retry.ReFriends.invite_aroundBody2(ReFriends.java:72)
        at com.netbout.client.retry.ReFriends$AjcClosure3.run(ReFriends.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:82)
        at com.netbout.client.retry.ReFriends.invite(ReFriends.java:72)
        at com.netbout.client.cached.CdFriends.invite_aroundBody0(CdFriends.java:69)
        at com.netbout.client.cached.CdFriends$AjcClosure1.run(CdFriends.java:1)
```

**Comment by yegor256** [comment]
@dmzaytsev I also can't invite anyone to the bout from the web

**Comment by yegor256** [comment]
@dmzaytsev I think the problem is in `TkInvite`:

```
        final String check = new RqAlias(this.base, req)
            .user().aliases().check(guest);
        if (!check.isEmpty()) {
            throw new RsFailure(
                String.format("incorrect alias \"%s\", try again", guest)
            );
        }
```

should be `if (check.isEmpty()) {`, if we need that check at all. I don't really understand what this check is doing in `TkInvite`. this validation should happen in `Friends#invite()`, not here in the presentation layer.

**Comment by yegor256** [comment]
@dmzaytsev would be great if we can fix that ASAP, since it's blocking many things now... :(

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by dmzaytsev** [comment]
@yegor256 I will look into

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by yegor256** [comment]
@dmzaytsev keep in mind that if you just fix this bug and release the next version 2.23, we will get 300+ new commits into production. that's rather risky, we may introduce other problems. it's better to release 2.22.1 right now, which will include 2.22 and a few new commits, which fix just this particular problem.

to do that you have to modify `release` script in `.rultor.yml` somehow... I'm thinking, how exactly...

**Comment by dmzaytsev** [comment]
@yegor256 actually we have 2.27 in production 

![image](https://cloud.githubusercontent.com/assets/9972909/13134712/60c3ee86-d62b-11e5-9356-1372f7cf0bc6.png)

**Comment by yegor256** [comment]
@dmzaytsev hm.. why don't we have a Github release for it??

**Comment by dmzaytsev** [comment]
@yegor256 it is not match to latest release due bug in rultor settings

**Comment by dmzaytsev** [comment]
@yegor256 we have the fix for it https://github.com/yegor256/netbout/pull/1018

**Comment by dmzaytsev** [comment]
@yegor256 you have modified `pom.xml` several weeks ago
it were changes related to coverall stats

**Comment by yegor256** [comment]
@dmzaytsev I understand now. OK, let's fix and release ASAP

**Comment by dmzaytsev** [comment]
@karato please see PR #1024

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.28`

**Comment by dmzaytsev** [comment]
@yegor256 done
please check the invitation

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by yegor256** [comment]
@dmzaytsev invitation works, thanks

**Comment by dmzaytsev** [comment]
@yegor256 please reopen ticket
I am not assigned yet to this one

**Comment by karato** [comment]
@yegor256 there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-d00bf676`

**Comment by dmzaytsev** [comment]
@karato assign me

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev of course, the task is yours, go ahead

**Comment by karato** [comment]
> @karato please see PR #1024

@dmzaytsev will take a look, thanks

**Comment by karato** [comment]
> @karato assign me

@dmzaytsev this task was already yours, go ahead

**Comment by dmzaytsev** [comment]
@yegor256 fixed in #1024 please close the ticket

**Comment by dmzaytsev** [comment]
@yegor256  fixed in #1024 please close the ticket

**Comment by dmzaytsev** [comment]
@yegor256 fixed in #1024 please close the ticket

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by karato** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thank you, good quality is always good :)

**Comment by karato** [comment]
@dmzaytsev 10 mins was added to the account of @ypshenychka (for QA review), in transaction 78637238; **30 mins** added to your account (payment number `78637260`), many thanks for your contribution! 94 hours and 30 mins spent here.; +30 added to your rating, current score is: [+3554](http://www.netbout.com/b/35166?open=rating)
