### ISSUE TITLE
thread in group 'main' interrupted

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#1025]
I'm seeing this in logs, a lot:

```
[ERROR] 55aa664 com.netbout.rest.TkAppFallback: java.lang.IllegalStateException: thread 'BkParallel-32' in group 'main' interrupted 	
at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:183) 	
at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1) 	
at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140) 	
at com.netbout.email.EmBout.number(EmBout.java:84) 	
at com.netbout.rest.bout.TkIndex.act(TkIndex.java:83) 	
at com.netbout.rest.bout.FkBout$2.act(FkBout.java:102) 	
at com.netbout.rest.bout.FkBout$1.act(FkBout.java:77) 	
at org.takes.facets.fork.FkRegex.route(FkRegex.java:189) 	
at org.takes.facets.fork.FkWrap.route(FkWrap.java:61) 	
at org.takes.facets.fork.TkFork.act(TkFork.java:101) 	
at org.takes.tk.TkWrap.act(TkWrap.java:61) 	
at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152) 	
at org.takes.facets.fork.FkRegex.route(FkRegex.java:189) 	
at org.takes.facets.fork.TkFork.act(TkFork.java:101) 	
at com.netbout.rest.FkRegistered$1.route(FkRegistered.java:70) 	
at org.takes.facets.fork.FkWrap.route(FkWrap.java:61) 	
at org.takes.facets.fork.TkFork.act(TkFork.java:101) 	
at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82) 	
at org.takes.facets.fork.TkFork.act(TkFork.java:101) 	
at org.takes.facets.auth.TkAuth.act(TkAuth.java:109) 	
at org.takes.facets.auth.TkAuth.act(TkAuth.java:  89) 	
at org.takes.tk.TkWrap.act(TkWrap.java:61) 	
at org.takes.facets.forward.TkForward.act(TkForward.java:68) 	
at org.takes.facets.fallback.TkFallback.route(TkFallback.java:80) 	
at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:50) 	
at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:62) 	
at org.takes.tk.TkWrap.act(TkWrap.java:61) 	
at org.takes.tk.TkWrap.act(TkWrap.java:61) 	
at org.takes.facets.flash.TkFlash.act(TkFlash.java:106) 	
at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67) 	
at org.takes.tk.TkWrap.act(TkWrap.java:61) 	
at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72) 	
at org.takes.tk.TkWrap.act(TkWrap.java:61) 	
at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:  71) 	
at org.takes.tk.TkWrap.act(TkWrap.java:61) 	
at org.takes.tk.TkWrap.act(TkWrap.java:61) 	
at org.takes.http.BkBasic.print(BkBasic.java:99) 	
at org.takes.http.BkBasic.accept(BkBasic.java:77) 	
at org.takes.http.BkSafe$1.accept(BkSafe.java:51) 	
at org.takes.http.BkWrap.accept(BkWrap.java:52) 	
at org.takes.http.BkTimeable$BkThreads.accept(BkTimeable.java:95) 	
at org.takes.http.BkWrap.accept(BkWrap.java:52) 	
at org.takes.http.BkParallel$1$1.run(BkParallel.java:90) 	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 	
at java.lang.Thread.run(Thread.java:745)  
```

**Comment by yegor256** [comment]
@dmzaytsev now it works OK, I don't see this exception any more. what's interesting, right after this exception disappeared, I see this:

```
Feb 19 00:23:31 www.netbout.com user:  [WARN] 55aa664 com.netbout.cached.CdFriends: #iterate(): '[CdFriend(origin=DyFriend(name=alex)), CdFriend(o..140.. CdFriend(origin=DyFriend(name=yegor256))]' in 1.09min (too slow!) 
Feb 19 00:23:31 www.netbout.com user:  [WARN] 55aa664 com.netbout.email.EmFriends: #iterate(): '[CdFriend(origin=DyFriend(name=alex)), CdFriend(o..140.. CdFriend(origin=DyFriend(name=yegor256))]' in 1.09min (too slow!) 
Feb 19 00:23:34 www.netbout.com user:  [WARN] 55aa664 com.jcabi.dynamo.retry.ReValve: #fetch(): attempt #1/3 failed with java.io.IOException in 50s (50s in total): com.amazonaws.AbortedException: ;  
Feb 19 00:23:44 www.netbout.com user:  [WARN] 55aa664 com.netbout.spi.Friends$Search: #exists('alice'): true in 1.29min (too slow!) 
Feb 19 00:23:44 www.netbout.com user:  [WARN] 55aa664 com.netbout.spi.Friends$Search: #exists('alex'): true in 1.29min (too slow!) 
Feb 19 00:23:44 www.netbout.com user:  [WARN] 55aa664 com.jcabi.dynamo.AwsIterator: #hasNext(): true in 1.00min (too slow!) 
Feb 19 00:23:44 www.netbout.com user:  [WARN] 55aa664 com.jcabi.dynamo.retry.ReIterator: #hasNext(): true in 1.00min (too slow!) 
Feb 19 00:23:44 www.netbout.com user:  [WARN] 55aa664 com.netbout.cached.CdFriends: #iterate(): '[CdFriend(origin=DyFriend(name=alex)), CdFriend(o..148.. CdFriend(origin=DyFriend(name=yegor256))]' in 1.00min (too slow!) 
Feb 19 00:23:44 www.netbout.com user:  [WARN] 55aa664 com.netbout.email.EmFriends: #iterate(): '[CdFriend(origin=DyFriend(name=alex)), CdFriend(o..148.. CdFriend(origin=DyFriend(name=yegor256))]' in 1.00min (too slow!) 
Feb 19 00:23:44 www.netbout.com user:  [WARN] 55aa664 com.netbout.spi.Friends$Search: #exists('alex'): true in 1.00min (too slow!) 
```

**Comment by yegor256** [comment]
@dmzaytsev we're having some serious problem on production now. I can't understand what's causing it. 50% of requests take longer than 30 seconds and get interrupted by `BkTimeable`. DynamoDB is not the cause of the problem now. maybe it's Heroku, where load average is now close to 30.0

**Comment by yegor256** [comment]
@dmzaytsev also, please upgrade to Takes 0.31.2 in this ticket

**Comment by dmzaytsev** [comment]
@yegor256  I have no idea what's causing the loading
do you think upgrade to Takes 0.31.2 may help?

**Comment by yegor256** [comment]
@dmzaytsev upgrade to Takes 0.31.2 will give a bit more information in logs. also, let's merge this: #1030

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by yegor256** [comment]
@dmzaytsev maybe you have other ideas about why the application is so slow? This happened just recently. This problem exists for the last 2-3 days. And it's a serious issue. Looks like some defect was released recently. Any ideas?

**Comment by yegor256** [comment]
@dmzaytsev we need to fix this urgently

**Comment by dmzaytsev** [comment]
@yegor256 all of the log records related to Dynamo
 I think it is a Dynamo problem

**Comment by dmzaytsev** [comment]
@yegor256 however there is a similar issue https://github.com/yegor256/netbout/issues/983
but it was unreproducable

**Comment by yegor256** [comment]
@dmzaytsev Dynamo metrics show less than 10% load of the maximum capacity. this means that Dynamo is not throttling us at all...

**Comment by dmzaytsev** [comment]
@yegor256 I can't upgrate to latest Takes right now. There are a lot of broken tests.
Could you make this https://github.com/yegor256/takes/issues/620 urgent ?

**Comment by karato** [comment]
@yegor256 attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by karato** [comment]
@yegor256 many thanks for the bug report, I added 15 mins to your acc, transaction `000-168c4fae`

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev of course, the task is yours, go ahead

**Comment by yegor256** [comment]
@dmzaytsev this is very serious now. I will try to fix it myself

**Comment by yegor256** [comment]
@rultor release, tag is `2.22.1`

**Comment by yegor256** [comment]
@dmzaytsev the problem was here: 446d995

**Comment by dmzaytsev** [comment]
@yegor256 but these files were modified several months ago
why do you think it is the reason of the issue?

> yegor256 commented 3 hours ago
> @dmzaytsev the problem was here: 446d995

**Comment by dmzaytsev** [comment]
@yegor256 it seems the problem not resolved yet
please provide detailed logs

**Comment by yegor256** [comment]
@dmzaytsev well, the site works fast now, logs are clean... maybe some other things I've done above helped?

**Comment by dmzaytsev** [comment]
@yegor256  I got an application error on Netbout about 30 mins ago
please check the logs

**Comment by dmzaytsev** [comment]
@yegor256 I got a new one right now
![image](https://cloud.githubusercontent.com/assets/9972909/13243687/ac3cf4b6-da22-11e5-9f19-014ceedc5c09.png)

**Comment by yegor256** [comment]
@dmzaytsev are you logged in via Google?

**Comment by yegor256** [comment]
@dmzaytsev if yes, check this: https://github.com/yegor256/netbout/issues/1038

**Comment by yegor256** [comment]
@dmzaytsev logs:

```
ERROR 1465137 com.netbout.rest.TkAppFallback: java.lang.IllegalStateException: [GET http://www.netbout.com/?PsByFlag=PsGoogle&code=4%2FMY7nZ4PHN79-kGArt7U9sNxmt3JPfDsKWy1YdLkuZn8&state=http%3A%2F%2Fwww.netbout.com%2F] failed in 363ms: null 	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233) 	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:112) 	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54) 	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66) 	at org.takes.tk.TkWrap.act(TkWrap.java:61) 	at org.takes.tk.TkWrap.a...
Feb 23 07:42:18 www.netbout.com ...ct(TkWrap.java:  61) 	at org.takes.facets.flash.TkFlash.act(TkFlash.java:106) 	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67) 	at org.takes.tk.TkWrap.act(TkWrap.java:61) 	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72) 	at org.takes.tk.TkWrap.act(TkWrap.java:61) 	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71) 	at org.takes.tk.TkWrap.act(TkWrap.java:61) 	at org.takes.tk.TkWrap.act(TkWrap.java:61) 	at org.takes.http.BkBasic.print(BkBasic.java:100) 	at org.takes.http.BkBasic.accept(BkBasic.java:78) 	at org.takes.http.BkSafe$1.accept(BkSafe.java:51) 	at org.take...
Feb 23 07:42:18 www.netbout.com ...s.http.BkWrap.accept(BkWrap.java:  52) 	at org.takes.http.BkTimeable$BkThreads.accept(BkTimeable.java:106) 	at org.takes.http.BkWrap.accept(BkWrap.java:52) 	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 	at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.NullPointerException 	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:199) 	at org.takes.facets...
Feb 23 07:42:18 www.netbout.com ....auth.social.PsGoogle.parse(PsGoogle.java:  199) 	at org.takes.facets.auth.social.PsGoogle.fetch(PsGoogle.java:151) 	at org.takes.facets.auth.social.PsGoogle.enter(PsGoogle.java:129) 	at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:107) 	at org.takes.facets.auth.PsChain.enter(PsChain.java:70) 	at com.netbout.rest.PsTwice.enter(PsTwice.java:70) 	at org.takes.facets.auth.TkAuth.act(TkAuth.java:86) 	at org.takes.tk.TkWrap.act(TkWrap.java:61) 	at org.takes.facets.forward.TkForward.act(TkForward.java:68) 	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:85) 	... 22 more  
```

**Comment by dmzaytsev** [comment]
no, logged via github

**Comment by yegor256** [comment]
@dmzaytsev that's all I see in logs... only this exception. try again right now.

**Comment by dmzaytsev** [comment]
@yegor256 it works now but too slow

**Comment by yegor256** [comment]
@dmzaytsev now it's in your hands. I removed the critical problem. try to remove others too.

**Comment by dmzaytsev** [comment]
@yegor256 could you check heroku system logs?

**Comment by yegor256** [comment]
@dmzaytsev now it's this: https://github.com/yegor256/netbout/issues/1045

**Comment by karato** [comment]
@yegor256 there is a puzzle in this code `1025-adc69076`/#1047, we'll resolve it later

**Comment by karato** [comment]
@yegor256 the last puzzle `1025-adc69076`/#1047 originated from here solved

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1152](https://github.com/yegor256/netbout/issues/1152) is solved here.
