### ISSUE TITLE
can't login using Google OAuth

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#1038]
I can't login using Google OAuth:

```
java.lang.IllegalStateException: [GET http://www.netbout.com/?PsByFlag=PsGoogle&code=4%2FK5Q1j2CUMfMAxfWSDla2VboXMnI-RK-81XJ_9mWlP3I&state=http%3A%2F%2Fwww.netbout.com%2F] failed in 104ms: null
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:112)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:106)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:100)
	at org.takes.http.BkBasic.accept(BkBasic.java:78)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable$BkThreads.accept(BkTimeable.java:106)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:199)
	at org.takes.facets.auth.social.PsGoogle.parse(PsGoogle.java:199)
	at org.takes.facets.auth.social.PsGoogle.fetch(PsGoogle.java:151)
	at org.takes.facets.auth.social.PsGoogle.enter(PsGoogle.java:129)
	at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:107)
	at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
	at com.netbout.rest.PsTwice.enter(PsTwice.java:70)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:86)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:85)
	... 22 more
```

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tag bug added to this issue

**Comment by karato** [comment]
@yegor256 I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-07a829af`

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev yep, it is yours, go ahead

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.15`

**Comment by dmzaytsev** [comment]
@yegor256 could you check Netbout google auth settings?
on the side note is there any project that uses PsGoogle for an authentification?

**Comment by yegor256** [comment]
@dmzaytsev I don't have any... you can create your own Google account and check how it all works... I will check Google settings now

**Comment by dmzaytsev** [comment]
@karato more time

**Comment by karato** [comment]
> @karato more time

@dmzaytsev sure, take your time

**Comment by dmzaytsev** [comment]
@yegor256 you have to enable access to Google+ API for Google project related to Netbout Google account. As Takes PsGoogle uses that API

**Comment by yegor256** [comment]
@dmzaytsev I enabled Google+ API

**Comment by yegor256** [comment]
@dmzaytsev works fine now

**Comment by dmzaytsev** [comment]
@karato fixed in PR #1087

**Comment by karato** [comment]
> @karato fixed in PR #1087

@dmzaytsev thank you!

**Comment by karato** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thank you, good quality is always good ;)

**Comment by karato** [comment]
@dmzaytsev just added 10 mins to @elenavolokhova (for QA), payment ID is `85669340`; Thanks for your contribution, **30 mins** was added to your account, payment ID is `85669361`, 1274 hours and 14 mins spent total; +30 added to your rating, at the moment it is: [+1344](http://www.netbout.com/b/35166?open=rating)
