### ISSUE TITLE
Error on post a message to the bout 

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#1074]
This is the link http://www.netbout.com/b/36865
And the exception:

```
 Version: 2.22.14

Netbout team has already received a notification about this problem. We will investigate and fix as soon as possible. In the mean time, click "Back" button in your browser and try again. It may work :)

If you want to help our project, please post the following exception stacktrace to our Github account.

java.lang.IllegalStateException: [GET http://www.netbout.com/b/36865] failed in 235ms: org.xml.sax.SAXParseException; lineNumber: 104; columnNumber: 63; Attribute name "extends" associated with an element type "T" must be followed by the ' = ' character.
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
    at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:199)
    at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsPrint.printBody(RsPrint.java:161)
    at org.takes.rs.RsPrint.print(RsPrint.java:114)
    at org.takes.http.BkBasic.print(BkBasic.java:100)
    at org.takes.http.BkBasic.accept(BkBasic.java:78)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable$BkThreads.accept(BkTimeable.java:106)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: org.xml.sax.SAXParseException; lineNumber: 104; columnNumber: 63; Attribute name "extends" associated with an element type "T" must be followed by the ' = ' character.
    at org.takes.rs.RsPrettyXML.getDocType(RsPrettyXML.java:206)
    at org.takes.rs.RsPrettyXML.prepareDocType(RsPrettyXML.java:160)
    at org.takes.rs.RsPrettyXML.transform(RsPrettyXML.java:137)
    at org.takes.rs.RsPrettyXML.make(RsPrettyXML.java:104)
    at org.takes.rs.RsPrettyXML.head(RsPrettyXML.java:88)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithCookie.previousValue(RsWithCookie.java:174)
    at org.takes.rs.RsWithCookie.access$100(RsWithCookie.java:63)
    at org.takes.rs.RsWithCookie$1.head(RsWithCookie.java:124)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:115)
    at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
    at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:187)
    ... 19 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 104; columnNumber: 63; Attribute name "extends" associated with an element type "T" must be followed by the ' = ' character.
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
    at org.takes.rs.RsPrettyXML.getDocType(RsPrettyXML.java:202)
    ... 31 more
```

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@longtimeago since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@longtimeago thank you for reporting this, I added 15 mins to your acc, transaction `79372620`
