### ISSUE TITLE
Entering an invalid email causes Internal Application Error

### ISSUE THREAD

**Issue by wild-lotus** [yegor256/netbout#1080]
At the page to change email `/acc/index`, if you enter an invalid email, like "a@b.c", you get an Internal Application Error.

```
java.lang.IllegalStateException: [POST http://localhost:8080/acc/save] failed in 12ms: Email 'a@b.c' is wrong
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:112)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.flash.TkFlash.act(TkFlash.java:106)
    at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.http.FtCLI$1.act(FtCLI.java:83)
    at org.takes.http.BkBasic.print(BkBasic.java:100)
    at org.takes.http.BkBasic.accept(BkBasic.java:78)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable$BkThreads.accept(BkTimeable.java:106)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.netbout.spi.Alias$InvalidEmailException: Email 'a@b.c' is wrong
    at com.netbout.dynamo.DyAlias.email_aroundBody10(DyAlias.java:134)
    at com.netbout.dynamo.DyAlias$AjcClosure11.run(DyAlias.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
    at com.netbout.dynamo.DyAlias.email(DyAlias.java:133)
    at com.netbout.cached.CdAlias.email_aroundBody16(CdAlias.java:101)
    at com.netbout.cached.CdAlias$AjcClosure17.run(CdAlias.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
    at com.netbout.cached.CdAlias.email(CdAlias.java:101)
    at com.netbout.email.EmAlias.email_aroundBody10(EmAlias.java:118)
    at com.netbout.email.EmAlias$AjcClosure11.run(EmAlias.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
    at com.netbout.email.EmAlias.email(EmAlias.java:118)
    at com.netbout.rest.account.TkSaveEmail.act(TkSaveEmail.java:104)
    at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
    at org.takes.facets.fork.TkFork.act(TkFork.java:101)
    at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
    at org.takes.facets.fork.TkFork.act(TkFork.java:101)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
    at org.takes.facets.fork.TkFork.act(TkFork.java:101)
    at com.netbout.rest.TkWithAliasHeader.act(TkWithAliasHeader.java:68)
    at com.netbout.rest.FkRegistered$1.route(FkRegistered.java:70)
    at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
    at org.takes.facets.fork.TkFork.act(TkFork.java:101)
    at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
    at org.takes.facets.fork.TkFork.act(TkFork.java:101)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.forward.TkForward.act(TkForward.java:68)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:85)
    ... 23 more
```

**Comment by dmzaytsev** [comment]
@CarlosGines you expect a friendly error message, right?

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@carlosgines attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by CarlosGines** [comment]
> @CarlosGines you expect a friendly error message, right?
@dmzaytsev Yes, users should never see the error page under normal circumstances.

**Comment by CarlosGines** [comment]
> @carlosgines attached this issue to milestone "3.1" (let me know if this is wrong)

@karato I don't know how we work with milestones, so I can't tell if it is wrong. Is there somewhere I could read about it, or could you give me a short explanation?

**Comment by karato** [comment]
@carlosgines many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `AP-25243432H82539259`

**Comment by TommyWind** [comment]
created PR #1091 for this.

**Comment by TommyWind** [comment]
PR updated.

**Comment by TommyWind** [comment]
@dmzaytsev PR updated.
