### ISSUE TITLE
Bout name too long causes Internal Application Error

### ISSUE THREAD

**Issue by CarlosGines** [yegor256/netbout#1081]
If you rename a bout with a title longer than 200 characters, you get an Internal Application Error:
```
java.lang.IllegalStateException: [POST http://localhost:8080/b/1457580216737/rename] failed in 3ms: bout name is too long
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:112)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:100)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.FtCLI$1.act(FtCLI.java:83)
	at org.takes.http.BkBasic.print(BkBasic.java:100)
	at org.takes.http.BkBasic.accept(BkBasic.java:78)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable$BkThreads.accept(BkTimeable.java:106)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: bout name is too long
	at com.netbout.dynamo.DyBout.rename_aroundBody8(DyBout.java:119)
	at com.netbout.dynamo.DyBout$AjcClosure9.run(DyBout.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.netbout.dynamo.DyBout.rename(DyBout.java:115)
	at com.netbout.cached.CdBout.rename_aroundBody14(CdBout.java:96)
	at com.netbout.cached.CdBout$AjcClosure15.run(CdBout.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.netbout.cached.CdBout.rename(CdBout.java:96)
	at com.netbout.email.EmBout.rename_aroundBody8(EmBout.java:104)
	at com.netbout.email.EmBout$AjcClosure9.run(EmBout.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.netbout.email.EmBout.rename(EmBout.java:104)
	at com.netbout.rest.bout.TkRename.act(TkRename.java:70)
	at com.netbout.rest.bout.FkBout$2.act(FkBout.java:102)
	at com.netbout.rest.bout.FkBout$1.act(FkBout.java:77)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at com.netbout.rest.TkWithAliasHeader.act(TkWithAliasHeader.java:68)
	at com.netbout.rest.FkRegistered$1.route(FkRegistered.java:70)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:85)
	... 23 more
```

**Comment by dmzaytsev** [comment]
@CarlosGines did you get the exception on latest master?

**Comment by CarlosGines** [comment]
@dmzaytsev Yes. Just be sure to enter more than 200 characters.

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@carlosgines since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@carlosgines thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-40297242CU0435737`
