### ISSUE TITLE
505 error if alias is occupied

### ISSUE THREAD

**Issue by 2686747** [yegor256/netbout#1083]
If i try to get existing alias after authorization with github i see following exception stacktrace

Internal Application Error
Version: 2.22.14
`
java.lang.IllegalStateException: [POST http://www.netbout.com/login/register] failed in 665ms: alias 'alice' is occupied
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:112)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.flash.TkFlash.act(TkFlash.java:106)
    at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.http.BkBasic.print(BkBasic.java:100)
    at org.takes.http.BkBasic.accept(BkBasic.java:78)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable$BkThreads.accept(BkTimeable.java:106)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: alias 'alice' is occupied
    at com.netbout.dynamo.DyAliases.add_aroundBody2(DyAliases.java:147)
    at com.netbout.dynamo.DyAliases$AjcClosure3.run(DyAliases.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
    at com.netbout.dynamo.DyAliases.add(DyAliases.java:139)
    at com.netbout.cached.CdAliases.add_aroundBody2(CdAliases.java:77)
    at com.netbout.cached.CdAliases$AjcClosure3.run(CdAliases.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
    at com.netbout.cached.CdAliases.add(CdAliases.java:77)
    at com.netbout.email.EmAliases.add_aroundBody2(EmAliases.java:80)
    at com.netbout.email.EmAliases$AjcClosure3.run(EmAliases.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
    at com.netbout.email.EmAliases.add(EmAliases.java:80)
    at com.netbout.rest.login.TkRegister.act(TkRegister.java:72)
    at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
    at org.takes.facets.fork.TkFork.act(TkFork.java:101)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
    at org.takes.facets.fork.TkFork.act(TkFork.java:101)
    at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
    at org.takes.facets.fork.TkFork.act(TkFork.java:101)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.forward.TkForward.act(TkForward.java:68)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:85)
    ... 22 more
`

**Comment by 2686747** [comment]
P.S.: it happens when i press 'register' button before i see message "this alias is occupied"

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@2686747 I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
@2686747 thanks for the report, I topped your acc for 15 mins, payment ID `56e2b10c92575230ef000001`

**Comment by 2686747** [comment]
@karato thanks a lot

**Comment by karato** [comment]
> @karato thanks a lot

@2686747 sure, you are welcome
