### ISSUE TITLE
Google Authentican

### ISSUE THREAD

**Issue by amitMist** [yegor256/netbout#1089]
```
java.lang.IllegalStateException: [GET http://www.netbout.com/?PsByFlag=PsGoogle&code=4%2FJIcFapWPa0GDd5tLSaIn28h4-vfZdiJrqSsp--udYe0&state=http%3A%2F%2Fwww.netbout.com%2F] failed in 66ms: HTTP response status is not equal to 200:
400 Bad Request [https://accounts.google.com/o/oauth2/token]
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="31,30,29,28,27,26,25"
Server: GSE
X-Content-Type-Options: nosniff
P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
Date: Sat, 12 Mar 2016 09:18:54 GMT
Alternate-Protocol: 443:quic,p=1
Accept-Ranges: none
X-Frame-Options: SAMEORIGIN
Cache-Control: private, max-age=0
Vary: Accept-Encoding
Set-Cookie: NID=77=YkrJdTxPObN3x_dfYW28n0leQaUFxRwD4bP9p_ds6jXe5HN2e9rjdAZzcPGVoAMq_yYXYBI5247vZY10qtrmY0gFdSB7YcgpBiLxWfRkPLUy6Ua9BrkzD20NwefRm1Qa;Domain=.google.com;Path=/;Expires=Sun, 11-Sep-2016 09:18:54 GMT;HttpOnly
Expires: Sat, 12 Mar 2016 09:18:54 GMT
X-XSS-Protection: 1; mode=block
Content-Type: application/json; charset=utf-8

{
  "error" : "invalid_grant",
  "error_description" : "Invalid code."
}
Expected: HTTP response with status 200
     but: was <400 Bad Request [https://accounts.google.com/o/oauth2/token]
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="31,30,29,28,27,26,25"
Server: GSE
X-Content-Type-Options: nosniff
P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
Date: Sat, 12 Mar 2016 09:18:54 GMT
Alternate-Protocol: 443:quic,p=1
Accept-Ranges: none
X-Frame-Options: SAMEORIGIN
Cache-Control: private, max-age=0
Vary: Accept-Encoding
Set-Cookie: NID=77=YkrJdTxPObN3x_dfYW28n0leQaUFxRwD4bP9p_ds6jXe5HN2e9rjdAZzcPGVoAMq_yYXYBI5247vZY10qtrmY0gFdSB7YcgpBiLxWfRkPLUy6Ua9BrkzD20NwefRm1Qa;Domain=.google.com;Path=/;Expires=Sun, 11-Sep-2016 09:18:54 GMT;HttpOnly
Expires: Sat, 12 Mar 2016 09:18:54 GMT
X-XSS-Protection: 1; mode=block
Content-Type: application/json; charset=utf-8

{
  "error" : "invalid_grant",
  "error_description" : "Invalid code."
}>
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:112)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
    at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.http.BkBasic.print(BkBasic.java:100)
    at org.takes.http.BkBasic.accept(BkBasic.java:78)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: HTTP response status is not equal to 200:
400 Bad Request [https://accounts.google.com/o/oauth2/token]
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="31,30,29,28,27,26,25"
Server: GSE
X-Content-Type-Options: nosniff
P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
Date: Sat, 12 Mar 2016 09:18:54 GMT
Alternate-Protocol: 443:quic,p=1
Accept-Ranges: none
X-Frame-Options: SAMEORIGIN
Cache-Control: private, max-age=0
Vary: Accept-Encoding
Set-Cookie: NID=77=YkrJdTxPObN3x_dfYW28n0leQaUFxRwD4bP9p_ds6jXe5HN2e9rjdAZzcPGVoAMq_yYXYBI5247vZY10qtrmY0gFdSB7YcgpBiLxWfRkPLUy6Ua9BrkzD20NwefRm1Qa;Domain=.google.com;Path=/;Expires=Sun, 11-Sep-2016 09:18:54 GMT;HttpOnly
Expires: Sat, 12 Mar 2016 09:18:54 GMT
X-XSS-Protection: 1; mode=block
Content-Type: application/json; charset=utf-8

{
  "error" : "invalid_grant",
  "error_description" : "Invalid code."
}
Expected: HTTP response with status 200
     but: was <400 Bad Request [https://accounts.google.com/o/oauth2/token]
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="31,30,29,28,27,26,25"
Server: GSE
X-Content-Type-Options: nosniff
P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
Date: Sat, 12 Mar 2016 09:18:54 GMT
Alternate-Protocol: 443:quic,p=1
Accept-Ranges: none
X-Frame-Options: SAMEORIGIN
Cache-Control: private, max-age=0
Vary: Accept-Encoding
Set-Cookie: NID=77=YkrJdTxPObN3x_dfYW28n0leQaUFxRwD4bP9p_ds6jXe5HN2e9rjdAZzcPGVoAMq_yYXYBI5247vZY10qtrmY0gFdSB7YcgpBiLxWfRkPLUy6Ua9BrkzD20NwefRm1Qa;Domain=.google.com;Path=/;Expires=Sun, 11-Sep-2016 09:18:54 GMT;HttpOnly
Expires: Sat, 12 Mar 2016 09:18:54 GMT
X-XSS-Protection: 1; mode=block
Content-Type: application/json; charset=utf-8

{
  "error" : "invalid_grant",
  "error_description" : "Invalid code."
}>
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:111)
    at org.takes.facets.auth.social.PsGoogle.token(PsGoogle.java:173)
    at org.takes.facets.auth.social.PsGoogle.enter(PsGoogle.java:129)
    at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:107)
    at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
    at com.netbout.rest.PsTwice.enter(PsTwice.java:70)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:86)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.forward.TkForward.act(TkForward.java:68)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:85)
    ... 21 more
```

**Comment by karato** [comment]
@dmzaytsev please do something about this issue

**Comment by ekondrashev** [comment]
@yegor256 can't login to netbout - redirected to home page, and got "Bad Request" on google authentication chosen.
