### ISSUE TITLE
IllegalStateException: The element type "T" must be terminated by the matching end-tag

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#1099]
This appears requesting for the bout http://www.netbout.com/b/37013

```
java.lang.IllegalStateException: [GET http://www.netbout.com/b/37013] failed in 639ms: org.xml.sax.SAXParseException; lineNumber: 93; columnNumber: 109; The element type "T" must be terminated by the matching end-tag "".
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
    at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:199)
    at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsPrint.printBody(RsPrint.java:161)
    at org.takes.rs.RsPrint.print(RsPrint.java:114)
    at org.takes.http.BkBasic.print(BkBasic.java:100)
    at org.takes.http.BkBasic.accept(BkBasic.java:78)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: org.xml.sax.SAXParseException; lineNumber: 93; columnNumber: 109; The element type "T" must be terminated by the matching end-tag "".
    at org.takes.rs.RsPrettyXML.getDocType(RsPrettyXML.java:206)
    at org.takes.rs.RsPrettyXML.prepareDocType(RsPrettyXML.java:160)
    at org.takes.rs.RsPrettyXML.transform(RsPrettyXML.java:137)
    at org.takes.rs.RsPrettyXML.make(RsPrettyXML.java:104)
    at org.takes.rs.RsPrettyXML.head(RsPrettyXML.java:88)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:115)
    at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
    at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:187)
    ... 18 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 93; columnNumber: 109; The element type "T" must be terminated by the matching end-tag "".
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
    at org.takes.rs.RsPrettyXML.getDocType(RsPrettyXML.java:202)
    ... 31 more
```

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tag bug added to this issue

**Comment by karato** [comment]
@longtimeago I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@longtimeago thank you for the ticket reported, I topped your account for 15 mins, transaction `84295859`
