### ISSUE TITLE
conflict at com.jcabi.s3.AwsBucket.ocket

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#1100]
I'm getting this in production:

```
500 Internal Error [http://www.netbout.com/b/35087/upload?name=ledger&ctype=text/x-markdown&etag=003164cfc22d7c5a089b4008ad8538aa]
X-Takes-Millis: 10
Vary: Cookie
Date: Mon, 04 Apr 2016 21:58:23 GMT
X-Netbout-Version: 2.22.16 dd6ba63 2016-04-03T16:59:40
X-Takes-Version: 0.32.6 24e43a2 2016-03-10T00:51:32
Via: 1.1 vegur
Content-Type: text/html
Connection: close
Server: Cowboy

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Internal application error</title>
        <link href="/css/style.css?2.22.16" rel="stylesheet" type="text/css"/>
        <link rel="icon" type="image/gif" href="/favicon.ico"/>
    </head>
    <body style="padding: 1em;">
        <p>
            <a href="http://www.netbout.com/">
                <img src="//img.netbout.com/logo.svg?2.22.16"
                    style="width:113px;height:37px;"/>
            </a>
        </p>
        <p>
            <strong style="color: red;">
                Internal Application Error
            </strong>
        </p>
        <p>
            Version: <code>2.22.16</code>
        </p>
        <p>
            Netbout team has already received a notification about this
            problem. We will investigate and fix as soon as possible. In the
            mean time, click "Back" button in your browser and try
            again. It may work :)
        </p>
        <p>
            If you want to help our project, please post the following
            exception stacktrace to our
            <a href="https://github.com/yegor256/netbout/issues/new">Github</a> account.
        </p>
        <pre>java.lang.IllegalStateException: [POST http://www.netbout.com/b/35087/upload?ctype=text%2Fx-markdown&etag=003164cfc22d7c5a089b4008ad8538aa&name=ledger] failed in 5ms: HV000151: A method overriding another method must not alter the parameter constraint configuration, but method public com.jcabi.s3.Ocket com.jcabi.s3.AwsBucket.ocket(java.lang.String) changes the configuration of public abstract com.jcabi.s3.Ocket com.jcabi.s3.Bucket.ocket(java.lang.String).
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:112)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:100)
	at org.takes.http.BkBasic.accept(BkBasic.java:78)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.validation.ConstraintDeclarationException: HV000151: A method overriding another method must not alter the parameter constraint configuration, but method public com.jcabi.s3.Ocket com.jcabi.s3.AwsBucket.ocket(java.lang.String) changes the configuration of public abstract com.jcabi.s3.Ocket com.jcabi.s3.Bucket.ocket(java.lang.String).
	at org.hibernate.validator.internal.metadata.aggregated.rule.OverridingMethodMustNotAlterParameterConstraints.apply(OverridingMethodMustNotAlterParameterConstraints.java:24)
	at org.hibernate.validator.internal.metadata.aggregated.ExecutableMetaData$Builder.assertCorrectnessOfConfiguration(ExecutableMetaData.java:445)
	at org.hibernate.validator.internal.metadata.aggregated.ExecutableMetaData$Builder.build(ExecutableMetaData.java:364)
	at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataImpl$BuilderDelegate.build(BeanMetaDataImpl.java:611)
	at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataImpl$BeanMetaDataBuilder.build(BeanMetaDataImpl.java:514)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.createBeanMetaData(BeanMetaDataManager.java:168)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.getOrCreateBeanMetaData(BeanMetaDataManager.java:191)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.isConstrained(BeanMetaDataManager.java:135)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateParameters(ValidatorImpl.java:284)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateParameters(ValidatorImpl.java:242)
	at com.jcabi.aspects.aj.MethodValidator.validateMethod(MethodValidator.java:156)
	at com.jcabi.aspects.aj.MethodValidator.beforeMethod(MethodValidator.java:87)
	at com.jcabi.s3.AwsBucket.ocket_aroundBody4(AwsBucket.java:97)
	at com.jcabi.s3.AwsBucket$AjcClosure5.run(AwsBucket.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.s3.AwsBucket.ocket(AwsBucket.java:97)
	at com.netbout.dynamo.DyAttachment.save(DyAttachment.java:270)
	at com.netbout.dynamo.DyAttachment.write_aroundBody14(DyAttachment.java:216)
	at com.netbout.dynamo.DyAttachment$AjcClosure15.run(DyAttachment.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.netbout.dynamo.DyAttachment.write(DyAttachment.java:214)
	at com.netbout.cached.CdAttachment.write_aroundBody26(CdAttachment.java:112)
	at com.netbout.cached.CdAttachment$AjcClosure27.run(CdAttachment.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.netbout.cached.CdAttachment.write(CdAttachment.java:112)
	at com.netbout.email.EmAttachment.write_aroundBody14(EmAttachment.java:102)
	at com.netbout.email.EmAttachment$AjcClosure15.run(EmAttachment.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.netbout.email.EmAttachment.write(EmAttachment.java:102)
	at com.netbout.rest.bout.TkUpload.act(TkUpload.java:71)
	at com.netbout.rest.bout.FkBout$2.act(FkBout.java:102)
	at com.netbout.rest.bout.FkBout$1.act(FkBout.java:77)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at com.netbout.rest.TkWithAliasHeader.act(TkWithAliasHeader.java:68)
	at com.netbout.rest.FkRegistered$1.route(FkRegistered.java:70)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:85)
	... 21 more
```

It's a serious blocker, let's try to fix ASAP!

**Comment by yegor256** [comment]
@dmzaytsev I think we just need to upgrade to the latest jcabi-s3, where this will be fixed: https://github.com/jcabi/jcabi-s3/issues/44 (I'm working on it now). and, of course, we have to reproduce it first.

**Comment by yegor256** [comment]
@dmzaytsev 0.11.5 of jcabi-s3 should fix the problem

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by dmzaytsev** [comment]
@yegor256 I think it can't be reproduced in a test due to a unreachable code for the integration test
[DyAttachment.java#L270](
https://github.com/yegor256/netbout/blob/master/netbout-web%2Fsrc%2Fmain%2Fjava%2Fcom%2Fnetbout%2Fdynamo%2FDyAttachment.java#L270) is the saving to AWS bucket (when we have an attachment's size greater than 50k bytes)
For the integration test we are use LocalDynamo instance, there is no local AWS bucket I guess

So I going to bump up  jcabi-s3 to latest version

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by karato** [comment]
@yegor256 I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev the task is yours, please proceed

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.17`

**Comment by dmzaytsev** [comment]
@yegor256 fixed in #1101 please check again on production and close the issue if alright

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks a lot :)

**Comment by karato** [comment]
@dmzaytsev added 10 mins to @ypshenychka, for QA review, payment code is `82849715`... I added **1 hour** to your account, many thanks for working with the project (82849740)! The completion time here was 16 hours and 59 mins.... there is a bonus for fast delivery (m=1019)... +60 to your rating, your total score is [+2850](http://www.netbout.com/b/35166?open=rating)
