### ISSUE TITLE
attribute date not found

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#1103]
I am getting on production 

>Internal Application Error
Version: 2.22.17
Netbout team has already received a notification about this problem. We will investigate and fix as soon as possible. In the mean time, click "Back" button in your browser and try again. It may work :)
If you want to help our project, please post the following exception stacktrace to our Github account.
java.lang.IllegalStateException: [GET http://www.netbout.com/b/35166] failed in 26ms: attribute date not found
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
	at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:199)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:161)
	at org.takes.rs.RsPrint.print(RsPrint.java:114)
	at org.takes.http.BkBasic.print(BkBasic.java:100)
	at org.takes.http.BkBasic.accept(BkBasic.java:78)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: attribute date not found
	at com.jcabi.dynamo.AwsItem.get_aroundBody2(AwsItem.java:170)
	at com.jcabi.dynamo.AwsItem$AjcClosure3.run(AwsItem.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.dynamo.AwsItem.get(AwsItem.java:142)
	at com.netbout.dynamo.DyAttachment.date_aroundBody8(DyAttachment.java:172)
	at com.netbout.dynamo.DyAttachment$AjcClosure9.run(DyAttachment.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.netbout.dynamo.DyAttachment.date(DyAttachment.java:170)
	at com.netbout.cached.CdAttachment.date_aroundBody16(CdAttachment.java:94)
	at com.netbout.cached.CdAttachment$AjcClosure17.run(CdAttachment.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:308)
	at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:138)
	at com.netbout.cached.CdAttachment.date(CdAttachment.java:94)
	at com.netbout.email.EmAttachment.date_aroundBody8(EmAttachment.java:86)
	at com.netbout.email.EmAttachment$AjcClosure9.run(EmAttachment.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.netbout.email.EmAttachment.date(EmAttachment.java:86)
	at com.netbout.rest.bout.XeAttachment.make(XeAttachment.java:98)
	at com.netbout.rest.bout.XeAttachment.(XeAttachment.java:69)
	at com.netbout.rest.bout.TkIndex$2.transform(TkIndex.java:125)
	at com.netbout.rest.bout.TkIndex$2.transform(TkIndex.java:121)
	at org.takes.rs.xe.XeTransform$1.next(XeTransform.java:101)
	at org.takes.rs.xe.XeTransform$1.next(XeTransform.java:93)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:62)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:73)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:73)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:73)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.RsXembly.render(RsXembly.java:148)
	at org.takes.rs.xe.RsXembly.access$000(RsXembly.java:66)
	at org.takes.rs.xe.RsXembly$1.body(RsXembly.java:130)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithoutHeader$1.body(RsWithoutHeader.java:75)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrettyXML.make(RsPrettyXML.java:104)
	at org.takes.rs.RsPrettyXML.head(RsPrettyXML.java:88)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:115)
	at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:187)
	... 18 more

<hr id='w'>

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato assign me

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.2.18`

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.2.20`

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.3`

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.18`

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@dmzaytsev there is a puzzle in this code `1103-520ca7fd`, we'll resolve it later

**Comment by karato** [comment]
@dmzaytsev I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
> @karato assign me

@dmzaytsev of course, the task is yours, go ahead

**Comment by karato** [comment]
> @karato assign me

@dmzaytsev assigning yourself to your own tasks is a bad practice, according to our [five principles](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html) of bug tracking, try to avoid this in the future

**Comment by dmzaytsev** [comment]
@karato it was an urgent issue


> karato commented 34 minutes ago
> @karato assign me
> @dmzaytsev assigning yourself to your own tasks is a bad practice, according to our five principles of bug tracking, try to avoid this in the future

**Comment by dmzaytsev** [comment]
@karato fixed in #1104

I'm closing the issue

**Comment by karato** [comment]
> @karato fixed in #1104
> 
> I'm closing the issue

@dmzaytsev thank you!

**Comment by karato** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Quality is acceptable here, as far as this rule is not followed:

 >Problem reporter and problem solver are two different persons.
 
@dmzaytsev Please, try to avoid such cases in future.

**Comment by dmzaytsev** [comment]
@elenavolokhova sure
 it was an urgent issue

**Comment by elenavolokhova** [comment]
@karato Quality is acceptable here.

**Comment by karato** [comment]
> @karato Quality is acceptable here.

@elenavolokhova thanks a lot, next time everybody should try to make it better

**Comment by karato** [comment]
@dmzaytsev I added 10 mins to @elenavolokhova (for QA review) in transaction 83432261... Thanks so much! Your account was topped up for **1 hour** (transaction ID is `83432282`, the task took 1 hour and 16 mins)... there is a bonus for fast delivery (m=76)... +60 to your rating, your total score is [+2701](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@dmzaytsev the last puzzle `1103-520ca7fd`/#1107 originated from here solved

**Comment by 0pdd** [comment]
@dmzaytsev the only puzzle [#1156](https://github.com/yegor256/netbout/issues/1156) is solved here.
