### ISSUE TITLE
java.util.NoSuchElementException: attribute unseen not found

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#527]
```
java.util.NoSuchElementException: attribute unseen not found
	at com.jcabi.dynamo.AwsItem.get_aroundBody2(AwsItem.java:173)
	at com.jcabi.dynamo.AwsItem$AjcClosure3.run(AwsItem.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:200)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:128)
	at com.jcabi.dynamo.AwsItem.get(AwsItem.java:145)
	at com.netbout.dynamo.DyAttachment.unseen_aroundBody4(DyAttachment.java:145)
	at com.netbout.dynamo.DyAttachment$AjcClosure5.run(DyAttachment.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:200)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:128)
	at com.netbout.dynamo.DyAttachment.unseen(DyAttachment.java:140)
	at com.netbout.cached.CdAttachment.unseen_aroundBody8(CdAttachment.java:80)
	at com.netbout.cached.CdAttachment$AjcClosure9.run(CdAttachment.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:200)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:128)
	at com.netbout.cached.CdAttachment.unseen_aroundBody10(CdAttachment.java:80)
	at com.netbout.cached.CdAttachment$AjcClosure11.run(CdAttachment.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:277)
	at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:126)
	at com.netbout.cached.CdAttachment.unseen(CdAttachment.java:80)
	at com.netbout.rest.BoutRs.bundle(BoutRs.java:547)
```

**Comment by karato** [comment]
@yegor256 thanks, I added the "bug" tag

**Comment by karato** [comment]
I will find a developer for the task soon...

**Comment by karato** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-a92646aa`

**Comment by karato** [comment]
@yegor256 since the ticket has no milestone I set it to 3.1
