### ISSUE TITLE
list of recipients is NULL

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#539]
```
exception: java.lang.IllegalStateException: list of recipients is NULL
	at com.jcabi.email.Envelope$Strict.unwrap(Envelope.java:216)
	at com.jcabi.email.Postman$Default.send(Postman.java:128)
	at com.jcabi.email.postman.PostNoLoops.send(PostNoLoops.java:82)
	at com.netbout.email.EmAlias$1.send(EmAlias.java:75)
	at com.netbout.email.EmMessages.email(EmMessages.java:118)
	at com.netbout.email.EmMessages.post_aroundBody0(EmMessages.java:91)
	at com.netbout.email.EmMessages$AjcClosure1.run(EmMessages.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.email.EmMessages.post(EmMessages.java:89)
	at com.netbout.rest.BoutRs.post(BoutRs.java:323)
```

**Comment by yegor256** [comment]
root cause: https://github.com/jcabi/jcabi-email/issues/15

**Comment by yegor256** [comment]
@rultor release, tag is `2.12.1`

**Comment by yegor256** [comment]
@rultor release, tag is `2.12.1`
