### ISSUE TITLE
Empty multipart: multipart/alternative;

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#540]
```
java.io.IOException: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.IOException: javax.mail.MessagingException: Empty multipart: multipart/alternative; 
	boundary="----=_Part_3_1780627080.1420743305978"
	at com.jcabi.email.Postman$Default.send(Postman.java:139)
	at com.jcabi.email.postman.PostNoLoops.send(PostNoLoops.java:82)
	at com.netbout.email.EmAlias$1.send(EmAlias.java:75)
	at com.netbout.email.EmMessages.email(EmMessages.java:121)
	at com.netbout.email.EmMessages.post_aroundBody0(EmMessages.java:94)
	at com.netbout.email.EmMessages$AjcClosure1.run(EmMessages.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.email.EmMessages.post(EmMessages.java:89)
	at com.netbout.rest.BoutRs.post(BoutRs.java:323)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$VoidOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:167)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	at com.rexsl.core.RestfulServlet.service_aroundBody2(RestfulServlet.java:175)
	at com.rexsl.core.RestfulServlet$AjcClosure3.run(RestfulServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.rexsl.core.RestfulServlet.service_aroundBody4(RestfulServlet.java:174)
	at com.rexsl.core.RestfulServlet$AjcClosure5.run(RestfulServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.rexsl.core.RestfulServlet.service(RestfulServlet.java:174)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.rexsl.core.XsltFilter.filter(XsltFilter.java:169)
	at com.rexsl.core.XsltFilter.doFilter_aroundBody2(XsltFilter.java:138)
	at com.rexsl.core.XsltFilter$AjcClosure3.run(XsltFilter.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.rexsl.core.XsltFilter.doFilter_aroundBody4(XsltFilter.java:136)
	at com.rexsl.core.XsltFilter$AjcClosure5.run(XsltFilter.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.rexsl.core.XsltFilter.doFilter(XsltFilter.java:136)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.IOException: javax.mail.MessagingException: Empty multipart: multipart/alternative; 
	boundary="----=_Part_3_1780627080.1420743305978"
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1167)
	at com.jcabi.email.Postman$Default.send(Postman.java:132)
	... 70 more
Caused by: java.io.IOException: javax.mail.MessagingException: Empty multipart: multipart/alternative; 
	boundary="----=_Part_3_1780627080.1420743305978"
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:105)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1574)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1840)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1119)
	... 71 more

```

**Comment by yegor256** [comment]
@rultor release, tag is `2.12.2`

**Comment by yegor256** [comment]
@rultor release, tag is `2.12.2`

**Comment by yegor256** [comment]
@rultor release, tag is `2.12.2`
