### ISSUE TITLE
ProgressInputStream exception when uploading a big attachment

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#543]
```
exception: java.lang.IllegalArgumentException
	at com.amazonaws.event.ProgressInputStream.<init>(ProgressInputStream.java:76)
	at com.amazonaws.event.ProgressInputStream.<init>(ProgressInputStream.java:70)
	at com.amazonaws.event.RequestProgressInputStream.<init>(RequestProgressInputStream.java:28)
	at com.amazonaws.event.ProgressInputStream.inputStreamForRequest(ProgressInputStream.java:39)
	at com.amazonaws.http.AmazonHttpClient.beforeRequest(AmazonHttpClient.java:350)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:283)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3711)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1470)
	at com.jcabi.s3.AwsOcket.write_aroundBody10(AwsOcket.java:188)
	at com.jcabi.s3.AwsOcket$AjcClosure11.run(AwsOcket.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.s3.AwsOcket.write(AwsOcket.java:184)
	at com.netbout.dynamo.DyAttachment.save_aroundBody12(DyAttachment.java:267)
	at com.netbout.dynamo.DyAttachment$AjcClosure13.run(DyAttachment.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.dynamo.DyAttachment.save(DyAttachment.java:233)
	at com.netbout.dynamo.DyAttachment.write_aroundBody10(DyAttachment.java:217)
	at com.netbout.dynamo.DyAttachment$AjcClosure11.run(DyAttachment.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.dynamo.DyAttachment.write(DyAttachment.java:190)
	at com.netbout.cached.CdAttachment.write_aroundBody18(CdAttachment.java:99)
	at com.netbout.cached.CdAttachment$AjcClosure19.run(CdAttachment.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.cached.CdAttachment.write(CdAttachment.java:99)
	at com.netbout.email.EmAttachment.write_aroundBody10(EmAttachment.java:91)
	at com.netbout.email.EmAttachment$AjcClosure11.run(EmAttachment.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.email.EmAttachment.write(EmAttachment.java:91)
	at com.netbout.rest.BoutRs.attach(BoutRs.java:259)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by karato** [comment]
@yegor256 thanks, I added the "bug" tag

**Comment by karato** [comment]
I will find a developer for the task soon...

**Comment by karato** [comment]
@yegor256 many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `000-c826d82a`

**Comment by dmzaytsev** [comment]
@yegor256 Is this fixed already ? If so close the task please
If no let me know how to reproduce the issue

**Comment by yegor256** [comment]
@dmzaytsev right, it's gone

**Comment by karato** [comment]
@yegor256 I set milestone here to `3.1`, let me know if it is wrong
