### ISSUE TITLE
netbout.com fails with internal application error

### ISSUE THREAD

**Issue by darkled** [yegor256/netbout#544]
Opening http://www.netbout.com/ I get Internal Application Error:
```
date: Thu Jan 15 11:02:42 UTC 2015
code: NULL
message: java.lang.NoSuchFieldError: currentToken
exception_type: class java.lang.NoSuchFieldError
request_uri: /
servlet context path: "/"
requested: http://www.netbout.com//trap (GET) at www.netbout.com:80
request: null, -1 bytes
remote: 10.185.192.169:49031 (10.185.192.169)
servlet: "netbout" (API 3.0) at "Apache Tomcat/7.0.34"
headers:
  host: www.netbout.com
  connection: close
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  user-agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
  accept-encoding: gzip, deflate, sdch
  accept-language: ru,en-US;q=0.8,en;q=0.6,de;q=0.4
  cookie: Rexsl-Auth="17C8007A-FJHTTUUG-0097ASJE-79JMIT38-ELH3KCPI-6SQJGC9J-003M8OBI-DDM6AP00-6DK78T3G-ECT2UBR1-EPGN8OBI-ECN6EQBK-D1QM4TBJ-CLP66RRE-EHIMST1E-CDNMQBRL-5SPJ4DPL-70OJ6FRM-7KPKK==="
  via: 1.1 spbsrv-proxy.t-systems.ru (squid/3.1.10), 1.1 vegur
  x-forwarded-for: 10.233.17.226, 145.255.238.136
  cache-control: max-age=259200
  x-request-id: b449bf59-1113-4f74-b398-493d1ad06e91
  x-forwarded-proto: http
  x-forwarded-port: 80
  connect-time: 3
  x-request-start: 1421319737420
  total-route-time: 0

exception: java.lang.NoSuchFieldError: currentToken
	at com.amazonaws.services.dynamodbv2.model.transform.DescribeTableResultJsonUnmarshaller.unmarshall(DescribeTableResultJsonUnmarshaller.java:40)
	at com.amazonaws.services.dynamodbv2.model.transform.DescribeTableResultJsonUnmarshaller.unmarshall(DescribeTableResultJsonUnmarshaller.java:31)
	at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:106)
	at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:42)
	at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:929)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:663)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:292)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2908)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.describeTable(AmazonDynamoDBClient.java:795)
	at com.jcabi.dynamo.AwsTable.keys_aroundBody8(AwsTable.java:157)
	at com.jcabi.dynamo.AwsTable$AjcClosure9.run(AwsTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:282)
	at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:127)
	at com.jcabi.dynamo.AwsTable.keys(AwsTable.java:154)
	at com.jcabi.dynamo.AwsFrame.iterator_aroundBody0(AwsFrame.java:117)
	at com.jcabi.dynamo.AwsFrame$AjcClosure1.run(AwsFrame.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.AwsFrame.iterator(AwsFrame.java:117)
	at com.jcabi.dynamo.retry.ReFrame.iterator_aroundBody32(ReFrame.java:126)
	at com.jcabi.dynamo.retry.ReFrame$AjcClosure33.run(ReFrame.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:81)
	at com.jcabi.dynamo.retry.ReFrame.iterator(ReFrame.java:126)
	at com.google.common.collect.Iterables$8.iterator(Iterables.java:713)
	at com.google.common.collect.Iterables$8.iterator(Iterables.java:713)
	at com.google.common.collect.Lists.newArrayList(Lists.java:144)
	at com.netbout.cached.CdAliases.iterate_aroundBody4(CdAliases.java:82)
	at com.netbout.cached.CdAliases$AjcClosure5.run(CdAliases.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:282)
	at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:127)
	at com.netbout.cached.CdAliases.iterate(CdAliases.java:82)
	at com.netbout.email.EmAliases.iterate_aroundBody4(EmAliases.java:85)
	at com.netbout.email.EmAliases$AjcClosure5.run(EmAliases.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.email.EmAliases.iterate(EmAliases.java:85)
	at com.netbout.rest.BaseRs.identified(BaseRs.java:285)
	at com.netbout.rest.BaseRs.alias(BaseRs.java:257)
	at com.netbout.rest.InboxRs.bouts(InboxRs.java:113)
	at com.netbout.rest.InboxRs.inbox(InboxRs.java:79)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	at com.rexsl.core.RestfulServlet.service_aroundBody2(RestfulServlet.java:175)
	at com.rexsl.core.RestfulServlet$AjcClosure3.run(RestfulServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.rexsl.core.RestfulServlet.service_aroundBody4(RestfulServlet.java:174)
	at com.rexsl.core.RestfulServlet$AjcClosure5.run(RestfulServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.rexsl.core.RestfulServlet.service(RestfulServlet.java:174)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.rexsl.core.XsltFilter.filter(XsltFilter.java:169)
	at com.rexsl.core.XsltFilter.doFilter_aroundBody2(XsltFilter.java:138)
	at com.rexsl.core.XsltFilter$AjcClosure3.run(XsltFilter.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.rexsl.core.XsltFilter.doFilter_aroundBody4(XsltFilter.java:136)
	at com.rexsl.core.XsltFilter$AjcClosure5.run(XsltFilter.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.rexsl.core.XsltFilter.doFilter(XsltFilter.java:136)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yegor256** [comment]
@rultor release, tag is `2.12.3`

**Comment by darkled** [comment]
@yegor256 thanks, netbout.com is working now, I close the issue.

**Comment by darkled** [comment]
@yegor256 am I correct saying that such kind of tickets usually are not paid?

**Comment by yegor256** [comment]
@darkled you just closed it too soon :) in the future, don't close the ticket until you're paid

**Comment by darkled** [comment]
@yegor256 ah, ok, got it. thanks.

**Comment by karato** [comment]
@darkled thanks for reporting! I topped your account for 15 mins, transaction 50666098

**Comment by darkled** [comment]
fixed by @yegor256, closing it now.
