### ISSUE TITLE
Netbout is down

### ISSUE THREAD

**Issue by dpisarenko** [yegor256/netbout#545]
When I try to access http://www.netbout.com , I get a screen with the error message shown below.

Please fix it.

Message:
```
date: Thu Jan 15 11:05:33 UTC 2015
code: NULL
message: java.lang.NoSuchFieldError: currentToken
exception_type: class java.lang.NoSuchFieldError
request_uri: /
servlet context path: "/"
requested: http://www.netbout.com//trap (GET) at www.netbout.com:80
request: null, -1 bytes
remote: 10.38.131.237:43247 (10.38.131.237)
servlet: "netbout" (API 3.0) at "Apache Tomcat/7.0.34"
headers:
  host: www.netbout.com
  connection: close
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  user-agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36 OPR/24.0.1558.51 (Edition Next)
  accept-encoding: gzip,deflate,lzma,sdch
  accept-language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
  cookie: Rexsl-Auth="0DP40N80-29QN4RHQ-CTKN8Q3L-C8T32C9K-6CO3AD80-19I70QBJ-C5P6ARJB-DS036Q3K-EHO76EHF-5TGNCOBK-C5P76BJ7-D5Q6GTB2-ELPMASJ3-DTN78PBE-EGN66RRD-5TQIUC9H-6GPJ0D9L-7TR3QCOF"
  x-request-id: 7f446b11-1e64-4dac-a93e-049ffa5ccf15
  x-forwarded-for: 80.250.226.231
  x-forwarded-proto: http
  x-forwarded-port: 80
  via: 1.1 vegur
  connect-time: 0
  x-request-start: 1421319913480
  total-route-time: 0

exception: java.lang.NoSuchFieldError: currentToken
	at com.amazonaws.services.dynamodbv2.model.transform.DescribeTableResultJsonUnmarshaller.unmarshall(DescribeTableResultJsonUnmarshaller.java:40)
	at com.amazonaws.services.dynamodbv2.model.transform.DescribeTableResultJsonUnmarshaller.unmarshall(DescribeTableResultJsonUnmarshaller.java:31)
	at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:106)
	at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:42)
	at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:929)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:663)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:292)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2908)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.describeTable(AmazonDynamoDBClient.java:795)
	at com.jcabi.dynamo.AwsTable.keys_aroundBody8(AwsTable.java:157)
	at com.jcabi.dynamo.AwsTable$AjcClosure9.run(AwsTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:282)
	at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:127)
	at com.jcabi.dynamo.AwsTable.keys(AwsTable.java:154)
	at com.jcabi.dynamo.AwsFrame.iterator_aroundBody0(AwsFrame.java:117)
	at com.jcabi.dynamo.AwsFrame$AjcClosure1.run(AwsFrame.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.AwsFrame.iterator(AwsFrame.java:117)
	at com.jcabi.dynamo.retry.ReFrame.iterator_aroundBody32(ReFrame.java:126)
	at com.jcabi.dynamo.retry.ReFrame$AjcClosure33.run(ReFrame.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:81)
	at com.jcabi.dynamo.retry.ReFrame.iterator(ReFrame.java:126)
	at com.google.common.collect.Iterables$8.iterator(Iterables.java:713)
	at com.google.common.collect.Iterables$8.iterator(Iterables.java:713)
	at com.google.common.collect.Lists.newArrayList(Lists.java:144)
	at com.netbout.cached.CdAliases.iterate_aroundBody4(CdAliases.java:82)
	at com.netbout.cached.CdAliases$AjcClosure5.run(CdAliases.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:282)
	at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:127)
	at com.netbout.cached.CdAliases.iterate(CdAliases.java:82)
	at com.netbout.email.EmAliases.iterate_aroundBody4(EmAliases.java:85)
	at com.netbout.email.EmAliases$AjcClosure5.run(EmAliases.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.email.EmAliases.iterate(EmAliases.java:85)
	at com.netbout.rest.BaseRs.identified(BaseRs.java:285)
	at com.netbout.rest.BaseRs.alias(BaseRs.java:257)
	at com.netbout.rest.InboxRs.bouts(InboxRs.java:113)
	at com.netbout.rest.InboxRs.inbox(InboxRs.java:79)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	at com.rexsl.core.RestfulServlet.service_aroundBody2(RestfulServlet.java:175)
	at com.rexsl.core.RestfulServlet$AjcClosure3.run(RestfulServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.rexsl.core.RestfulServlet.service_aroundBody4(RestfulServlet.java:174)
	at com.rexsl.core.RestfulServlet$AjcClosure5.run(RestfulServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.rexsl.core.RestfulServlet.service(RestfulServlet.java:174)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.rexsl.core.XsltFilter.filter(XsltFilter.java:169)
	at com.rexsl.core.XsltFilter.doFilter_aroundBody2(XsltFilter.java:138)
	at com.rexsl.core.XsltFilter$AjcClosure3.run(XsltFilter.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.rexsl.core.XsltFilter.doFilter_aroundBody4(XsltFilter.java:136)
	at com.rexsl.core.XsltFilter$AjcClosure5.run(XsltFilter.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.rexsl.core.XsltFilter.doFilter(XsltFilter.java:136)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dpisarenko** [comment]
Seems to be a duplicate of https://github.com/yegor256/netbout/issues/544 .
