### ISSUE TITLE
netbout failed with OutOfMemoryError

### ISSUE THREAD

**Issue by alevohin** [yegor256/netbout#549]
Netbout failed with OOM Error. Need to investigate and increase memory for it.

Information about error:

```
date: Mon Jan 19 07:11:20 UTC 2015
code: NULL
message: java.lang.OutOfMemoryError: unable to create new native thread
exception_type: class java.lang.OutOfMemoryError
request_uri: /login
servlet context path: "/"
requested: http://www.netbout.com//trap (GET) at www.netbout.com:80
request: null, -1 bytes
servlet: "netbout" (API 3.0) at "Apache Tomcat/7.0.34"
headers:
  host: www.netbout.com
  connection: close
  cache-control: max-age=0
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  user-agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
  accept-encoding: gzip, deflate, sdch
  accept-language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
  x-request-id: 56eb75df-303b-4898-b1ad-6bd643840c2e
  x-forwarded-proto: http
  x-forwarded-port: 80
  via: 1.1 vegur
  connect-time: 1
  x-request-start: 1421651480256
  total-route-time: 0

exception: java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1047)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1091)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.jcabi.http.request.JdkRequest$1.send(JdkRequest.java:108)
	at com.jcabi.http.request.BaseRequest.fetchResponse(BaseRequest.java:299)
	at com.jcabi.http.request.BaseRequest.fetch(BaseRequest.java:214)
	at com.rexsl.page.auth.Github.token(Github.java:165)
	at com.rexsl.page.auth.Github.identity_aroundBody0(Github.java:117)
	at com.rexsl.page.auth.Github$AjcClosure1.run(Github.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.rexsl.page.auth.Github.identity(Github.java:103)
	at com.rexsl.page.auth.AuthInset.ofProviders(AuthInset.java:241)
	at com.rexsl.page.auth.AuthInset.identity_aroundBody6(AuthInset.java:140)
	at com.rexsl.page.auth.AuthInset$AjcClosure7.run(AuthInset.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.rexsl.page.auth.AuthInset.identity_aroundBody8(AuthInset.java:140)
	at com.rexsl.page.auth.AuthInset$AjcClosure9.run(AuthInset.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:282)
	at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:127)
	at com.rexsl.page.auth.AuthInset.identity(AuthInset.java:140)
	at com.netbout.rest.LoginRs.login(LoginRs.java:59)
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	at com.rexsl.core.RestfulServlet.service_aroundBody2(RestfulServlet.java:175)
	at com.rexsl.core.RestfulServlet$AjcClosure3.run(RestfulServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.rexsl.core.RestfulServlet.service_aroundBody4(RestfulServlet.java:174)
	at com.rexsl.core.RestfulServlet$AjcClosure5.run(RestfulServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.rexsl.core.RestfulServlet.service(RestfulServlet.java:174)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.rexsl.core.XsltFilter.filter(XsltFilter.java:169)
	at com.rexsl.core.XsltFilter.doFilter_aroundBody2(XsltFilter.java:138)
	at com.rexsl.core.XsltFilter$AjcClosure3.run(XsltFilter.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.rexsl.core.XsltFilter.doFilter_aroundBody4(XsltFilter.java:136)
	at com.rexsl.core.XsltFilter$AjcClosure5.run(XsltFilter.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.rexsl.core.XsltFilter.doFilter(XsltFilter.java:136)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by karato** [comment]
I'll ask someone to take care of this task soon

**Comment by karato** [comment]
@alevohin thanks for the ticket, your account was topped for 15 mins, payment 50519684

**Comment by dmzaytsev** [comment]
@alevohin this issue fixed already
@yegor256 correct me if I wrong

**Comment by karato** [comment]
@alevohin since the ticket has no milestone I set it to 3.1

**Comment by alevohin** [comment]
@dmzaytsev could you please provide some additional info issue's fix?

**Comment by dmzaytsev** [comment]
@alevohin Netbout has been migrated to Takes.
We have no class  `com.netbout.rest.LoginRs` any more, that's why I think the issue fixed
But if you got the same error recently please let me know how I can reproduce this.
Thank you

**Comment by dmzaytsev** [comment]
@alevohin did I answer to your question? 
could you please close the ticket if so
or if you got the same error recently please let me know how I can reproduce this.

**Comment by karato** [comment]
@mbarbieri this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here. Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by alevohin** [comment]
@dmzaytsev Why do you suggest that problem was with jersey and not with `Takes`?

**Comment by dmzaytsev** [comment]
@alevohin I see `at com.netbout.rest.LoginRs.login(LoginRs.java:59)` in the trace
but we have no class `com.netbout.rest.LoginRs` any more.
Could you give us more information ? did you get same error after March 18?

**Comment by mbarbieri** [comment]
@alevohin @dmzaytsev I tried to reproduce the error in my local running 
```
ab -n 50000 -c 1000 http://localhost:8080/
```
and looking in visualvm for something strange, but I wasn't able to reproduce it.

**Comment by dmzaytsev** [comment]
@mbarbieri I think you can't reproduce it locally...

@karato this is postponed task

**Comment by yegor256** [comment]
@dmzaytsev I think we should close it, not postpone. This problem existed before we migrated to Takes. I believe it's gone.

**Comment by dmzaytsev** [comment]
@yegor256 The ticker reporter able to close the ticket, but @alevohin don't want do it and don't explain why :)
thats why I marked it as postponed

**Comment by alevohin** [comment]
@dmzaytsev I did not see OOM after March 18. @yegor256 confirmed that the problem has gone after migration. So I just close it, thank you!

**Comment by dmzaytsev** [comment]
@alevohin thanks!

**Comment by karato** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato There was no fix provided in this ticket, as the issue is not reproducible any more. So it shouldn't be paid. Quality is bad here.

**Comment by karato** [comment]
> @karato There was no fix provided in this ticket, as the issue is not reproducible any more. So it shouldn't be paid. Quality is bad here.

@elenavolokhova thanks a lot, noticing bad quality is what makes us better

**Comment by karato** [comment]
@mbarbieri 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 58669427
