### ISSUE TITLE
Netbout failed with NoSuchMethodError

### ISSUE THREAD

**Issue by pinaf** [yegor256/netbout#558]
Upon clicking on the Github login icon in the netbout homepage, this error occurs:
```
date: Sun Jan 25 20:53:08 UTC 2015
code: NULL
message: java.lang.NoSuchMethodError: com.jcabi.http.Response.as(Ljava/lang/Class;)Ljava/lang/Object;
exception_type: class java.lang.NoSuchMethodError
request_uri: /login
servlet context path: "/"
requested: http://www.netbout.com//trap (GET) at www.netbout.com:80
request: null, -1 bytes
remote: 10.38.42.185:45059 (10.38.42.185)
servlet: "netbout" (API 3.0) at "Apache Tomcat/7.0.34"
headers:
  host: www.netbout.com
  connection: close
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/39.0.2171.65 Chrome/39.0.2171.65 Safari/537.36
  referer: http://www.netbout.com/login
  accept-encoding: gzip, deflate, sdch
  accept-language: en-US,en;q=0.8
  x-request-id: 1a143be5-803e-4c10-9443-5bf388afb481
  x-forwarded-for: 201.53.22.254
  x-forwarded-proto: http
  x-forwarded-port: 80
  via: 1.1 vegur
  connect-time: 4
  x-request-start: 1422219188396
  total-route-time: 0

exception: java.lang.NoSuchMethodError: com.jcabi.http.Response.as(Ljava/lang/Class;)Ljava/lang/Object;
	at com.rexsl.page.auth.Github.token(Github.java:165)
	at com.rexsl.page.auth.Github.identity_aroundBody0(Github.java:117)
	at com.rexsl.page.auth.Github$AjcClosure1.run(Github.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.rexsl.page.auth.Github.identity(Github.java:103)
	at com.rexsl.page.auth.AuthInset.ofProviders(AuthInset.java:241)
	at com.rexsl.page.auth.AuthInset.identity_aroundBody6(AuthInset.java:140)
	at com.rexsl.page.auth.AuthInset$AjcClosure7.run(AuthInset.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.rexsl.page.auth.AuthInset.identity_aroundBody8(AuthInset.java:140)
	at com.rexsl.page.auth.AuthInset$AjcClosure9.run(AuthInset.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:282)
	at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:127)
	at com.rexsl.page.auth.AuthInset.identity(AuthInset.java:140)
	at com.netbout.rest.LoginRs.login(LoginRs.java:59)
	at sun.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	at com.rexsl.core.RestfulServlet.service_aroundBody2(RestfulServlet.java:175)
	at com.rexsl.core.RestfulServlet$AjcClosure3.run(RestfulServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.rexsl.core.RestfulServlet.service_aroundBody4(RestfulServlet.java:174)
	at com.rexsl.core.RestfulServlet$AjcClosure5.run(RestfulServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.rexsl.core.RestfulServlet.service(RestfulServlet.java:174)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.rexsl.core.XsltFilter.filter(XsltFilter.java:169)
	at com.rexsl.core.XsltFilter.doFilter_aroundBody2(XsltFilter.java:138)
	at com.rexsl.core.XsltFilter$AjcClosure3.run(XsltFilter.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.rexsl.core.XsltFilter.doFilter_aroundBody4(XsltFilter.java:136)
	at com.rexsl.core.XsltFilter$AjcClosure5.run(XsltFilter.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.rexsl.core.XsltFilter.doFilter(XsltFilter.java:136)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yegor256** [comment]
@rultor release, tag is `2.13.4`

**Comment by yegor256** [comment]
@pinaf should be fine now, thanks

**Comment by pinaf** [comment]
@yegor256 yup. thanks.
