### ISSUE TITLE
post a message causes Internal Application Error

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#592]
when I post a message  I got the error 

```
Netbout team has already received a notification about this problem. We will investigate and fix as soon as possible. In the mean time, click "Back" button in your browser and try again. It may work :)
If you want to help our project, please post the following exception stacktrace to our Github account.
java.lang.NoSuchMethodError: com.sun.mail.util.TraceInputStream.(Ljava/io/InputStream;Lcom/sun/mail/util/MailLogger;)V
	at com.sun.mail.smtp.SMTPTransport.initStreams(SMTPTransport.java:2014)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1936)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:654)
	at javax.mail.Service.connect(Service.java:291)
	at com.jcabi.email.wire.SMTP.connect(SMTP.java:100)
	at com.jcabi.email.Postman$Default.send(Postman.java:129)
	at com.jcabi.email.postman.PostNoLoops.send(PostNoLoops.java:82)
	at com.netbout.email.EmAlias$1.send(EmAlias.java:75)
	at com.netbout.email.EmMessages.email(EmMessages.java:121)
	at com.netbout.email.EmMessages.post_aroundBody0(EmMessages.java:94)
	at com.netbout.email.EmMessages$AjcClosure1.run(EmMessages.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.email.EmMessages.post(EmMessages.java:89)
	at com.netbout.rest.bout.TkPost.act(TkPost.java:67)
	at com.netbout.rest.bout.FkBout$3.act(FkBout.java:110)
	at com.netbout.rest.bout.FkBout$2.act(FkBout.java:88)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at com.netbout.rest.bout.FkBout.route(FkBout.java:80)
	at com.netbout.rest.bout.FkBout.access$000(FkBout.java:51)
	at com.netbout.rest.bout.FkBout$1.route(FkBout.java:64)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:99)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.TkFork.act(TkFork.java:99)
	at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
	at org.takes.facets.fork.TkFork.act(TkFork.java:99)
	at org.takes.facets.forward.TkForward.act(TkForward.java:62)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:113)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:78)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:48)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:60)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:104)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:65)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:70)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:69)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.http.BkBasic.print(BkBasic.java:98)
	at org.takes.http.BkBasic.accept(BkBasic.java:76)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yegor256** [comment]
@dmzaytsev very strange... looking into it

**Comment by dmzaytsev** [comment]
@yegor256  I sent four messages today and got this error four times

**Comment by yegor256** [comment]
@dmzaytsev it works fine on my laptop, just confirmed with an integration test :(

**Comment by yegor256** [comment]
@dmzaytsev something is wrong with JVM in Heroku or our way of deploying the app there

**Comment by yegor256** [comment]
@dmzaytsev asked this: http://stackoverflow.com/questions/30156048/java-lang-nosuchmethoderror-com-sun-mail-util-traceinputstream

**Comment by yegor256** [comment]
@dmzaytsev fixed, thanks to SO

**Comment by yegor256** [comment]
@rultor release, tag is `2.14.1`
