### ISSUE TITLE
java.lang.NoSuchMethodError: com.sun.mail.util.TraceInputStream...

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#595]
```
java.lang.NoSuchMethodError: com.sun.mail.util.TraceInputStream.(Ljava/io/InputStream;Lcom/sun/mail/util/MailLogger;)V
	at com.sun.mail.smtp.SMTPTransport.initStreams(SMTPTransport.java:2039)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1959)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:656)
	at javax.mail.Service.connect(Service.java:291)
	at com.jcabi.email.wire.SMTP.connect(SMTP.java:100)
```

similar to #592

**Comment by yegor256** [comment]
@rultor release, tag is `2.14.6`

**Comment by yegor256** [comment]
@rultor release, tag is `2.14.6`
