### ISSUE TITLE
com.netbout.rest.MarkdownTest fails under windows

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#604]
`com.netbout.rest.MarkdownTest` fails when the project builds under windows

> Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.767 sec <<< FAILURE! - in com.netbout.rest.MarkdownTest
formatsTextFragmentsToHtml(com.netbout.rest.MarkdownTest)  Time elapsed: 0.524 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: "<p>hi, \n<em>dude</em>!</p>"
     but: was "<p>hi, \r\n<em>dude</em>!</p>"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.netbout.rest.MarkdownTest.formatsTextFragmentsToHtml(MarkdownTest.java:111)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato set milestone to 3.0

**Comment by dmzaytsev** [comment]
@karato this task is postponed

**Comment by karato** [comment]
@dmzaytsev we will find someone to do this task, soon

**Comment by karato** [comment]
@dmzaytsev since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
> @karato set milestone to 3.0

@dmzaytsev sure, milestone set to 3.0

**Comment by karato** [comment]
> @karato this task is postponed

@dmzaytsev sure, thanks, I added "postponed" tag to it

**Comment by karato** [comment]
@komaz please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here... Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by karato** [comment]
@dmzaytsev thanks for the ticket, your account was topped for 15 mins, payment 57701340

**Comment by yegor256** [comment]
@karato that's postponed

**Comment by komaz** [comment]
@dmzaytsev fixed in pull request #621

**Comment by dmzaytsev** [comment]
@komaz thanks!

**Comment by karato** [comment]
> @karato set milestone to 3.0

@dmzaytsev I set the milestone here to 3.0

**Comment by karato** [comment]
> @karato this task is postponed

@dmzaytsev OK, I labeled it as "postponed" tag

**Comment by karato** [comment]
> @karato this task is postponed

@dmzaytsev no problem, I will try to find somebody else

**Comment by karato** [comment]
> @karato that's postponed

@yegor256 got it, "postponed" tag here

**Comment by karato** [comment]
> @karato set milestone to 3.0

@dmzaytsev milestone is set to 3.0

**Comment by karato** [comment]
> @karato this task is postponed

@dmzaytsev OK, I labeled it as "postponed" tag

**Comment by yegor256** [comment]
@karato it's invalid

**Comment by dmzaytsev** [comment]
@yegor256 why do you mark this as invalid?

**Comment by yegor256** [comment]
@dmzaytsev because you closed it and it shouldn't be paid. or I'm wrong?

**Comment by dmzaytsev** [comment]
@yegor256 this issue  fixed in pull request #621
thats why I closed it

**Comment by yegor256** [comment]
@dmzaytsev my bad. I removed the "invalid" tag

**Comment by dmzaytsev** [comment]
@yegor256 thanks!

**Comment by karato** [comment]
@yegor256 please don't close the issue, ask @dmzaytsev to do this instead, since he is the author of it

**Comment by dmzaytsev** [comment]
@karato the issue resolved
I'm closing it

**Comment by karato** [comment]
> @karato set milestone to 3.0

@dmzaytsev I attached this issue to milestone `3.0`

**Comment by karato** [comment]
> @karato this task is postponed

@dmzaytsev OK, I labeled it as "postponed" tag

**Comment by karato** [comment]
> @karato this task is postponed

@dmzaytsev I will assign somebody else to this issue

**Comment by karato** [comment]
> @karato that's postponed

@yegor256 got it, "postponed" tag here

**Comment by karato** [comment]
> @karato that's postponed

@yegor256 right, I will find someone else, no problem

**Comment by dmzaytsev** [comment]
@karato this task is completed already

**Comment by komaz** [comment]
@dmzaytsev should I expect to get paid for this issue?

**Comment by dmzaytsev** [comment]
@komaz I agree, you should get paid
@yegor256 @karato please pay attention on this ticket

**Comment by yegor256** [comment]
@karato pls add extra 30 mins to @komaz

**Comment by karato** [comment]
> @karato pls add extra 30 mins to @komaz 

@yegor256 I've sent 30 mins extra to @komaz in transaction ID "AP-2TK445388C3346358"
