### ISSUE TITLE
Can't run the server locally

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#605]
I try to run the server  `mvn clean install -DskipTests=true -Phit-refresh -Dport=8080`
and got error
> java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.netbout.dynamo.DyBase.<init>(DyBase.java:71)
        at com.netbout.Launch.main(Launch.java:62)
        ... 6 more

`DyBase.java:71': 
```
creds = new Credentials.Direct(
    creds, Integer.parseInt(System.getProperty("dynamo.port"))
);
```
Seems maven can't reserve a port for Dynamo instance.
I tried under windows and redhat linux.

@yegor256 do you know anybody ran Netbout locally under other operating systems besides Mac?

**Comment by yegor256** [comment]
@dmzaytsev try this:

```
mvn clean install -Phit-refresh -Dport=8080
```

The problem is that you skip tests and that's why local dynamodb doesn't start

**Comment by dmzaytsev** [comment]
@yegor256 thanks!

under windows a test fails, under linux I have a http proxy issue with another test ... :)
