### ISSUE TITLE
org.pegdown.ParsingTimeoutException

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#644]
I see this in production log every 15-30 minutes:

```
May 27 14:28:17 www.netbout.com user:  [WARN] 920c6bd com.netbout.rest.Markdown: 
#html(): attempt #1/3 failed with org.parboiled.errors.ParserRuntimeException 
in 13s (13s in total): Error while parsing action'Root/Sequence/ZeroOrMore/Sequence/Block/FirstOf/Para/Sequence/Inlines/Sequence/InlineOrIntermediateEndline/Sequence/Inline/Inline_Action1' 
at input position (line 1, pos 1): ... some text ... ^  org.pegdown.ParsingTimeoutException; null 
```

It's not an error, but a warning, since the failure happens only on the first attempt. The second attempt successfully renders the HTML, but pay attention to the timing: 13s! There is definitely something wrong.

**Comment by dmzaytsev** [comment]
@yegor256 we need more information here
I would turn verbose to true

**Comment by dmzaytsev** [comment]
@yegor256 please update this ticket when the error will occur.
the full stack trace should be in the log

**Comment by dmzaytsev** [comment]
@yegor256 any updates here ?

**Comment by yegor256** [comment]
@dmzaytsev this is what I see now:

```
May 28 21:30:11 www.netbout.com user:  [WARN] d25198d com.netbout.rest.Markdown: #html(): attempt #1 of 3 failed in 3s (3s waiting already) with org.parboiled.errors.ParserRuntimeException: Error while parsing action 'Root/Sequence/ZeroOrMore/Sequence/Block/FirstOf/Para/Sequence/Inlines/Sequence/InlineOrIntermediateEndline/Sequence/Inline/Inline_Action1' at input position (line 1, pos 1): Alexey Saenko, your rating +2077 is over 2000 (very good!), that's why I've added you to one of our campus teams ("thindeck") as a code reviewer. Hope you don't mind. Thanks...
May 28 21:30:11 www.netbout.com ...:  for your great contribution! ^  org.pegdown.ParsingTimeoutException 	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:366) 	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46) 	at org.parboiled.matchers.MemoMismatchesMatcher.match(MemoMismatchesMatcher.java:41) 	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77) 	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351) 	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46) 	at org...
May 28 21:30:11 www.netbout.com ....parboiled.parserunners.BasicParseRunner.match(BasicParseRunn:  77) 	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351) 	at org.parboiled.matchers.FirstOfMatcher.match(FirstOfMatcher.java:41) 	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77) 	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351) 	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46) 	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77) 	at org.par...
May 28 21:30:11 www.netbout.com ...boiled.MatcherContext.runMatcher(MatcherContext.java:  351) 	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46) 	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77) 	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351) 	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46) 	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77) 	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351) 	at org.parboiled.matcher...
May 28 21:30:11 www.netbout.com ...s.SequenceMatcher.match(SequenceMatcher.java:  46) 	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77) 	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351) 	at org.parboiled.matchers.FirstOfMatcher.match(FirstOfMatcher.java:41) 	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77) 	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351) 	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46) 	at org.parboiled.parserunners.Basi...
May 28 21:30:11 www.netbout.com ...cParseRunner.match(BasicParseRunner.java:  77) 	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351) 	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46) 	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77) 	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351) 	at org.parboiled.matchers.ZeroOrMoreMatcher.match(ZeroOrMoreMatcher.java:39) 	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77) 	at org.parboiled.MatcherContext....
May 28 21:30:11 www.netbout.com ...runMatcher(MatcherContext.java:  351) 	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46) 	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77) 	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351) 	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46) 	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77) 	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351) 	at org.parboiled.parserunners.BasicParseRunne...
May 28 21:30:11 www.netbout.com ...r.run(BasicParseRunner.java:  72) 	at org.parboiled.parserunners.ReportingParseRunner.runBasicMatch(ReportingParseRunner.java:86) 	at org.parboiled.parserunners.ReportingParseRunner.run(ReportingParseRunner.java:66) 	at org.parboiled.parserunners.AbstractParseRunner.run(AbstractParseRunner.java:81) 	at org.pegdown.Parser.parseToParsingResult(Parser.java:1517) 	at org.pegdown.Parser.parseInternal(Parser.java:1504) 	at org.pegdown.Parser.parse(Parser.java:85) 	at org.pegdown.PegDownProcessor.parseMarkdown(PegDownProcessor.java:...
May 28 21:30:11 www.netbout.com ...181):  	at org.pegdown.PegDownProcessor.markdownToHtml(PegDownProcessor.java:166) 	at org.pegdown.PegDownProcessor.markdownToHtml(PegDownProcessor.java:157) 	at org.pegdown.PegDownProcessor.markdownToHtml(PegDownProcessor.java:153) 	at org.pegdown.PegDownProcessor.markdownToHtml(PegDownProcessor.java:141) 	at org.pegdown.PegDownProcessor.markdownToHtml(PegDownProcessor.java:114) 	at com.netbout.rest.Markdown.html_aroundBody0(Markdown.java:80) 	at com.netbout.rest.Markdown$AjcClosure1.run(Markdown.java:1) 	at org.aspectj.runt...
```

**Comment by dmzaytsev** [comment]
@yegor256 I agree, a bug here, probably in Pegdown
but I can't reproduce it.. 

```
@Test
public void formatsTextInTime() throws Exception {
    long max = 0;
    for (int ind =0; ind < 10000; ++ind) {
        final long start = System.currentTimeMillis();
        final Markdown meta = new Markdown(
            "Alexey Saenko, your rating +2077 is over 2000 (very good!), that's why I've added you to one of our campus teams (\"thindeck\") as a code reviewer. Hope you don't mind. Thanks for your great contribution! "
        );
        MatcherAssert.assertThat(
            meta.html(),
            Matchers.containsString("Alexey Saenko, your rating")
        );
        final long finish = System.currentTimeMillis();
        if (max < (finish - start)) {
            max = (finish - start);
        }
        }
    MatcherAssert.assertThat(
        max,
        Matchers.lessThan(500L)
    );
}
```
unfortunately, right now I can't dispatch this ticket to a developer
it would be great if you had any idea or an advice how to reproduce the bug locally

**Comment by yegor256** [comment]
@dmzaytsev I have no idea either :( I think the best option here is to replace Pegdown with something else. But I tried some other library before (check git log on `Markdown` class), it was no good either

**Comment by dmzaytsev** [comment]
@yegor256 what do you think about the idea to use Github API for the markdown rendering ?
https://developer.github.com/v3/markdown/
It has limits for the rate calls per hour, but we can use the user's Github token for it. 5000 calls per hour will be enough...
Or we can create a few github accounts and use a token's pool for the API calls...
Or we can cache the rendered content into the dynamo table...
Or when the limit will be exceed we can use PegDown for the content rendering...
Or anything else...

**Comment by yegor256** [comment]
@dmzaytsev hm... it's not a bad idea at all. I like the option of caching inside DynamoDB. let's go for it!

**Comment by dmzaytsev** [comment]
@yegor256 please close this issue
it's a bug in Pegdown but we can't reproduce it
I'm keep in mind the idea about github markdown, I'll create a task for that later

**Comment by yegor256** [comment]
@dmzaytsev ok
