### ISSUE TITLE
550  previously hard-bounced

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#736]
I'm posting a message and getting this error:

```
java.io.IOException: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 550  previously hard-bounced

	at com.jcabi.email.Postman$Default.send(Postman.java:139)
	at com.jcabi.email.postman.PostNoLoops.send(PostNoLoops.java:82)
	at com.netbout.email.EmAlias$1.send(EmAlias.java:75)
	at com.netbout.email.EmMessages.email(EmMessages.java:134)
	at com.netbout.email.EmMessages.post_aroundBody0(EmMessages.java:104)
	at com.netbout.email.EmMessages$AjcClosure1.run(EmMessages.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.email.EmMessages.post(EmMessages.java:98)
	at com.netbout.rest.bout.TkPost.act(TkPost.java:67)
	at com.netbout.rest.bout.FkBout$3.act(FkBout.java:111)
	at com.netbout.rest.bout.FkBout$2.act(FkBout.java:89)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at com.netbout.rest.bout.FkBout.route(FkBout.java:81)
	at com.netbout.rest.bout.FkBout.access$000(FkBout.java:52)
	at com.netbout.rest.bout.FkBout$1.route(FkBout.java:65)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:99)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.TkFork.act(TkFork.java:99)
	at com.netbout.rest.FkRegistered$1.route(FkRegistered.java:70)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:99)
	at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
	at org.takes.facets.fork.TkFork.act(TkFork.java:99)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:107)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:87)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.forward.TkForward.act(TkForward.java:66)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:78)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:48)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:60)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:104)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:65)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:70)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:69)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 550  previously hard-bounced

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1949)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1195)
	at com.jcabi.email.Postman$Default.send(Postman.java:132)
	... 53 more
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550  previously hard-bounced

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1802)
	... 55 more
```

The message is posted, but not delivered by email

**Comment by yegor256** [comment]
@dmzaytsev this is why you don't get emails from Netbout

**Comment by dmzaytsev** [comment]
@yegor256 did you see this message before?
besides when you answering me?

**Comment by yegor256** [comment]
@dmzaytsev no. I see it only when I answer you.

**Comment by dmzaytsev** [comment]
@yegor256 It's my mistake, I set invalid email address during an experiment before this.

**Comment by yegor256** [comment]
@dmzaytsev but we should find a way to prevent this stacktrace... In the future, another user will make a similar mistake... I think we should check the email when it's being changed. Or maybe even ask for verification click

**Comment by dmzaytsev** [comment]
@yegor256 Yes, you're right we should verify the email before change it. But such error can be occur with valid email. The mailbox may be blocked or is full.
Anyway a stack trace instead a clear message is definitely wrong. 
We should catch a send mail error and display the error message like this `Sorry we can't send notification email to <alias>. SMTP error NNN. XXXXX  `.  
I propose do it in this ticket if you don't mind.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@yegor256 there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-89116272`

**Comment by karato** [comment]
@bdragan please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here... The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by bdragan** [comment]
@karato PR #802 created and ready for review.

**Comment by karato** [comment]
> @karato PR #802 created and ready for review.

@bdragan OK thanks

**Comment by dmzaytsev** [comment]
@bdragan you should ask the ticket reporter to close the ticket 
Also mention in which PR  the issue been resolved

**Comment by bdragan** [comment]
@yegor256 The PR #802 has been merged to master. This ticket can be closed. Thanks!

**Comment by yegor256** [comment]
@bdragan thanks!

**Comment by karato** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@elenavolokhova thanks for the review and a good remark

**Comment by karato** [comment]
@bdragan just added 10 mins to @elenavolokhova (for QA), payment ID is `66930257`... Thanks for your contribution, **30 mins** was added to your account, payment ID is `66930270`, 216 hours and 7 mins spent total... +30 added to your rating, at the moment it is: [+45](http://www.netbout.com/b/35709?open=rating)
