### ISSUE TITLE
Character #00 is in the restricted XML range

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#757]
I see this in production, after version 2.16 is released

```
java.lang.IllegalArgumentException: org.xembly.XmlContentException: Character #00 is in the restricted XML range #00-#08, see http://www.w3.org/TR/2004/REC-xml11-20040204/#charsets
	at org.xembly.Directives.set(Directives.java:411)
	at com.netbout.rest.bout.XeMessage.make(XeMessage.java:74)
	at com.netbout.rest.bout.XeMessage.(XeMessage.java:62)
	at com.netbout.rest.bout.TkIndex$3.transform(TkIndex.java:134)
	at com.netbout.rest.bout.TkIndex$3.transform(TkIndex.java:130)
	at org.takes.rs.xe.XeTransform$1.next(XeTransform.java:100)
	at org.takes.rs.xe.XeTransform$1.next(XeTransform.java:92)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:62)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:73)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:73)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:73)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.RsXembly.render(RsXembly.java:109)
	at org.takes.rs.xe.RsXembly.access$000(RsXembly.java:57)
	at org.takes.rs.xe.RsXembly$1.body(RsXembly.java:94)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsWithoutHeader$1.body(RsWithoutHeader.java:73)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:112)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.facets.fork.RsFork$1.body(RsFork.java:72)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsWithCookie$1.body(RsWithCookie.java:129)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:113)
	at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:99)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:132)
	at org.takes.rs.RsWithCookie$1.body(RsWithCookie.java:129)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:112)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:112)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:68)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:157)
	at org.takes.rs.RsPrint.print(RsPrint.java:111)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.xembly.XmlContentException: Character #00 is in the restricted XML range #00-#08, see http://www.w3.org/TR/2004/REC-xml11-20040204/#charsets
	at org.xembly.Arg.range(Arg.java:199)
	at org.xembly.Arg.legal(Arg.java:181)
	at org.xembly.Arg.(Arg.java:59)
	at org.xembly.SetDirective.(SetDirective.java:58)
	at org.xembly.Directives.set(Directives.java:409)
	... 59 more
```

I believe, we have to use `Xembler.escape()` to fix this. It's urgent

**Comment by dmzaytsev** [comment]
@yegor256 where you see this message? how to reproduce it?

**Comment by yegor256** [comment]
@dmzaytsev not sure how to reproduce... I see it when I open some bouts where I was able to talk before the release 2.16. I think we can reproduce it only in a unit test

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato this is urgent

**Comment by dmzaytsev** [comment]
@assign this to me please

**Comment by yegor256** [comment]
@rultor release, tag is `2.16.1`

**Comment by yegor256** [comment]
@dmzaytsev I made a quick fix, since it's very urgent. Let's create a proper test and fix it properly anyway

**Comment by dmzaytsev** [comment]
@yegor256 yes, i did it already 791064f

**Comment by dmzaytsev** [comment]
@karato assign this to me please

**Comment by karato** [comment]
@yegor256 I am aware of the task, give me some time to find a developer...

**Comment by karato** [comment]
@yegor256 I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
@yegor256 thank you for reporting this, I added 15 mins to your acc, transaction `000-136519b0`

**Comment by karato** [comment]
> @karato this is urgent

@dmzaytsev right, I added "urgent" label

**Comment by karato** [comment]
> @karato  assign this to me please

@dmzaytsev of course, the task is yours, go ahead

**Comment by karato** [comment]
> @karato assign this to me please

@dmzaytsev this task was already yours, go ahead

**Comment by dmzaytsev** [comment]
@yegor256 fixed in #762  please close the ticket

**Comment by dmzaytsev** [comment]
@karato this is not urgent any more

**Comment by karato** [comment]
> @karato this is not urgent any more

@dmzaytsev OK, I un-labeled it as "urgent" tag

**Comment by dmzaytsev** [comment]
@yegor256 ping 

> @yegor256 fixed in #762 please close the ticket

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@ypshenychka thank you :)

**Comment by karato** [comment]
@dmzaytsev just added 10 mins to @ypshenychka (for QA), payment ID is `63439733`; Thanks a lot, I just topped your account for **1 hour**, transaction ID `63439742`, total time was 19 hours and 47 mins; m=1187, that's why a bonus here for fast delivery; +60 added to your rating, at the moment it is: [+1564](http://www.netbout.com/b/35166?open=rating)
