### ISSUE TITLE
Had an error while I signed up through my gmail account. Have pasted the return error code. 

### ISSUE THREAD

**Issue by abilasharjunan** [yegor256/netbout#789]
javax.json.stream.JsonParsingException: Not Found
	at com.jcabi.http.response.JsonResponse$VerboseReader.readObject(JsonResponse.java:161)
	at org.takes.facets.auth.social.PsGoogle.fetch(PsGoogle.java:150)
	at org.takes.facets.auth.social.PsGoogle.enter(PsGoogle.java:129)
	at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:108)
	at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
	at com.netbout.rest.PsTwice.enter(PsTwice.java:70)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:84)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.forward.TkForward.act(TkForward.java:66)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:78)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:48)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:60)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:104)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:65)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:70)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:69)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.json.stream.JsonParsingException: Unexpected char 78 at (line no=1, column no=1, offset=0)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:532)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:415)
	at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:222)
	at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:101)
	at com.jcabi.http.response.JsonResponse$VerboseReader.readObject(JsonResponse.java:159)
	... 29 more

**Comment by dmzaytsev** [comment]
@abilasharjunan we have already the ticket #786 for this bug

**Comment by dmzaytsev** [comment]
@abilasharjunan please close this ticket

**Comment by dmzaytsev** [comment]
@karato please put invalid tag here
and close this ticket

**Comment by dmzaytsev** [comment]
@yegor256 could you close this? thank you
