### ISSUE TITLE
JSR-303 validator failed to initialize: Unable to instantiate Configuration

### ISSUE THREAD

**Issue by hs3180** [yegor256/netbout#795]
After excluded MarkdownTest described in #767 , netbout-web building process still failed leaving following information:

    [INFO] --- jcabi-dynamodb-maven-plugin:0.7:start (dynamodb-integration-test) @ netbout-web --- 
    九月 19, 2015 3:16:48 上午 org.hibernate.validator.internal.util.Version <clinit> 
    INFO: HV000001: Hibernate Validator 5.1.0.Final
    [ERROR] JSR-303 validator failed to initialize: Unable to instantiate Configuration. (see  http://www.jcabi.com/jcabi-aspects/jsr-303.html)
    [INFO] jcabi-aspects 0.15/1409f87 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
    [INFO] #start(D:\\netbout\\netbout-web\\target\\dynamodb-dist, 59515, 'C:\\Program Files\\Java\\jdk1.7.0_79\\jre', []): in 19ms
    [INFO]
    [INFO] --- jcabi-dynamodb-maven-plugin:0.7:create-tables (dynamodb-integration-test) @ netbout-web ---

my environment

OS: windows 10 simplified chinese home edition with mingw64

    $ java -version
    java version "1.7.0_79"
    Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
    Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
    Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

    $ mvn -version
    Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T19:57:37+08:00)
    Maven home: C:\apache-maven-3.3.3
    Java version: 1.7.0_79, vendor: Oracle Corporation
    Java home: C:\Program Files\Java\jdk1.7.0_79\jre
    Default locale: zh_CN, platform encoding: UTF-8
    OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "windows"
    Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

**Comment by dmzaytsev** [comment]
@hs3180 `JSR-303 validator failed to initialize: Unable to instantiate Configuration` It's just warning message,
please provide other error messages after that

**Comment by hs3180** [comment]
@dmzaytsev I am sorry for pasting the wrong error report. The really error report is following after add "-X -e" parameter

    [ERROR] PermGen space -> [Help 1]
    java.lang.OutOfMemoryError: PermGen space
            at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1781)
            at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:196)
            at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:97)
            at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
            at sun.security.pkcs.PKCS7.parseSignedData(PKCS7.java:299)
            at sun.security.pkcs.PKCS7.parse(PKCS7.java:158)
            at sun.security.pkcs.PKCS7.parse(PKCS7.java:126)
            at sun.security.pkcs.PKCS7.<init>(PKCS7.java:108)
            at sun.security.util.SignatureFileVerifier.<init>(SignatureFileVerifier.java:97)
            at java.util.jar.JarVerifier.processEntry(JarVerifier.java:296)
            at java.util.jar.JarVerifier.update(JarVerifier.java:228)
            at java.util.jar.JarFile.initializeVerifier(JarFile.java:348)
            at java.util.jar.JarFile.getInputStream(JarFile.java:415)
            at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:775)
            at sun.misc.Resource.cachedInputStream(Resource.java:77)
            at sun.misc.Resource.getByteBuffer(Resource.java:160)
            at java.net.URLClassLoader.defineClass(URLClassLoader.java:436)
            at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
            at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:215)
            at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
            at java.security.AccessController.doPrivileged(Native Method)
            at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
            at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
            at sun.security.jca.ProviderList.getProvider(ProviderList.java:232)
    [ERROR]
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError
    [INFO] #stop(51521): in 206µs
    Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

I added PermSize options to JAVA as following

    export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8 -XX:PermSize=64m -XX:MaxPermSize=128m"

netbout-web pass the unit-test now. then I tried to start a local netbout-web server, 

    mvn clean install -Phit-refresh -Dport=8080

server started successful

	[INFO] --- exec-maven-plugin:1.3:java (start-takes-server) @ netbout-web ---
	[WARNING] Warning: killAfter is now deprecated. Do you need it ? Please comment on MEXEC-6.
	[INFO]
	[INFO] --- exec-maven-plugin:1.3:exec (casperjs-install) @ netbout-web ---
	Cloning into 'casperjs-install'...
	[INFO]
	[INFO] --- exec-maven-plugin:1.3:java (start-server) @ netbout-web ---
	[WARNING] Warning: killAfter is now deprecated. Do you need it ? Please comment on MEXEC-6.

but when I opened browser to localhost:8080, it gave me **No data received.
ERR_EMPTY_RESPONSE**

I have tried telnet

    telnet localhost 8080

link was established. but server returned nothing. I have sent some random character to the server, it still had no response.

**Comment by dmzaytsev** [comment]
@hs3180 unfortunately I can't reproduce this issue...
does the error is stable on your end?
could you provide a few lines before and after this? I need to know broken test name

**Comment by dmzaytsev** [comment]
@hs3180 ping

**Comment by hs3180** [comment]
@dmzaytsev 
The error is **stable**. Below is the whole tail of console log if I didn't set a larger PermSize:

    [INFO] --- jcabi-dynamodb-maven-plugin:0.7:create-tables (dynamodb-integration-test) @ netbout-web ---
    [DEBUG] Configuring mojo com.jcabi:jcabi-dynamodb-maven-plugin:0.7:create-tables from plugin realm ClassRealm[plugin>com.jcabi:jcabi-dynamodb-maven-plugin:0.7, parent: sun.misc.Launcher$AppClassLoader@47415dbf]
    [DEBUG] Configuring mojo 'com.jcabi:jcabi-dynamodb-maven-plugin:0.7:create-tables' with basic configurator -->
    [DEBUG]   (f) endpoint = http://localhost
    [DEBUG]   (f) key = AAAAABBBBBAAAAABBBBB
    [DEBUG]   (f) port = 51267
    [DEBUG]   (f) secret = ABCDABCDABCDABCDABCDABCDABCDABCDABCDABCD
    [DEBUG]   (s) skip = false
    [DEBUG]   (f) tables = [D:\dev\java\netbout\netbout-web/src/test/dynamodb/aliases.json, D:\dev\java\netbout\netbout-web/src/test/dynamodb/friends.json, D:\dev\java\netbout\netbout-web/src/test/dynamodb/messages.json, D:\dev\java\netbout\netbout-web/src/test/dynamodb/attachments.json]
    [DEBUG] -- end configuration --
    [INFO] >> 2015-09-30 10:27:15.353:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:51267
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO]
    [INFO] netbout ............................................ SUCCESS [  1.032 s]
    [INFO] netbout-spi ........................................ SUCCESS [  6.108 s]
    [INFO] netbout-client ..................................... SUCCESS [ 16.731 s]
    [INFO] netbout-web ........................................ FAILURE [01:35 min]
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 02:00 min
    [INFO] Finished at: 2015-09-30T10:27:17+08:00
    [INFO] Final Memory: 61M/740M
    [INFO] ------------------------------------------------------------------------
    [ERROR] PermGen space -> [Help 1]
    java.lang.OutOfMemoryError: PermGen space
            at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1781)
            at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:196)
            at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:97)
            at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
            at sun.security.pkcs.PKCS7.parseSignedData(PKCS7.java:299)
            at sun.security.pkcs.PKCS7.parse(PKCS7.java:158)
            at sun.security.pkcs.PKCS7.parse(PKCS7.java:126)
            at sun.security.pkcs.PKCS7.<init>(PKCS7.java:108)
            at sun.security.util.SignatureFileVerifier.<init>(SignatureFileVerifier.java:97)
            at java.util.jar.JarVerifier.processEntry(JarVerifier.java:296)
            at java.util.jar.JarVerifier.update(JarVerifier.java:228)
            at java.util.jar.JarFile.initializeVerifier(JarFile.java:348)
            at java.util.jar.JarFile.getInputStream(JarFile.java:415)
            at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:775)
            at sun.misc.Resource.cachedInputStream(Resource.java:77)
            at sun.misc.Resource.getByteBuffer(Resource.java:160)
            at java.net.URLClassLoader.defineClass(URLClassLoader.java:436)
            at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
            at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:215)
            at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
            at java.security.AccessController.doPrivileged(Native Method)
            at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
            at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
            at sun.security.jca.ProviderList.getProvider(ProviderList.java:232)
    [ERROR]
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError
    [INFO] #stop(51267): in 234µs
    Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

**Comment by dmzaytsev** [comment]
@hs3180 I have no idea how a future developer of this ticket can reproduce the issue...
sorry I can't set bug tag here

**Comment by yegor256** [comment]
@hs3180 check this out: http://stackoverflow.com/questions/88235/dealing-with-java-lang-outofmemoryerror-permgen-space-error

**Comment by dmzaytsev** [comment]
@hs3180  Sorry I can't set bug tag here. it is not reproducible.
http://www.yegor256.com/2014/04/13/bugs-are-welcome.html#what-is-a-bug?
Please close the ticket

**Comment by hs3180** [comment]
@dmzaytsev 
ok, I will try to reproduce this bug in a ec2 instance if I can.
