### ISSUE TITLE
Internal Application Error Version: 2.17.1 Netbout team has already received a notification about this problem. We will investigate and fix as soon as possible. In the mean time, click "Back" button in your browser and try again. It may work

### ISSUE THREAD

**Issue by ashishsabhaya** [yegor256/netbout#808]
javax.json.stream.JsonParsingException: Not Found
	at com.jcabi.http.response.JsonResponse$VerboseReader.readObject(JsonResponse.java:161)
	at org.takes.facets.auth.social.PsGoogle.fetch(PsGoogle.java:150)
	at org.takes.facets.auth.social.PsGoogle.enter(PsGoogle.java:129)
	at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:108)
	at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
	at com.netbout.rest.PsTwice.enter(PsTwice.java:70)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:84)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.forward.TkForward.act(TkForward.java:66)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:78)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:48)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:60)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:104)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:65)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:70)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:69)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.json.stream.JsonParsingException: Unexpected char 78 at (line no=1, column no=1, offset=0)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:532)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:415)
	at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:222)
	at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:101)
	at com.jcabi.http.response.JsonResponse$VerboseReader.readObject(JsonResponse.java:159)
	... 29 more

**Comment by ashishsabhaya** [comment]
I found this error while clicked on g+ inside netbout.com, please resolve it.

**Comment by dmzaytsev** [comment]
@ashishsabhaya thanks for reporting
we have ticket #786 for this issue. I hope it will be resolved soon

**Comment by dmzaytsev** [comment]
@ashishsabhaya the issue fixed please close the ticket

**Comment by dmzaytsev** [comment]
@yegor256 close the ticket please

**Comment by yegor256** [comment]
@dmzaytsev in the future, you can just ask a PM to close it as invalid, see http://www.teamed.io/policy.html#36
