### ISSUE TITLE
Long bout name produces Stack Trace

### ISSUE THREAD

**Issue by Rossiar** [yegor256/netbout#817]
I start a new bout and rename the bout as below:

![image](https://cloud.githubusercontent.com/assets/1635940/10558999/96b506ec-74dd-11e5-8a11-9a2e1d9e24da.png)

I am redirected to the following page:

```
Internal Application Error
Version: 2.18
Netbout team has already received a notification about this problem. We will investigate and fix as soon as possible. In the mean time, click "Back" button in your browser and try again. It may work :)
If you want to help our project, please post the following exception stacktrace to our Github account.
java.lang.IllegalArgumentException: bout name is too long
    at com.netbout.dynamo.DyBout.rename_aroundBody8(DyBout.java:119)
    at com.netbout.dynamo.DyBout$AjcClosure9.run(DyBout.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
    at com.netbout.dynamo.DyBout.rename(DyBout.java:115)
    at com.netbout.cached.CdBout.rename_aroundBody14(CdBout.java:96)
    at com.netbout.cached.CdBout$AjcClosure15.run(CdBout.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
    at com.netbout.cached.CdBout.rename(CdBout.java:96)
    at com.netbout.email.EmBout.rename_aroundBody8(EmBout.java:104)
    at com.netbout.email.EmBout$AjcClosure9.run(EmBout.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
    at com.netbout.email.EmBout.rename(EmBout.java:104)
    at com.netbout.rest.bout.TkRename.act(TkRename.java:70)
    at com.netbout.rest.bout.FkBout$3.act(FkBout.java:111)
    at com.netbout.rest.bout.FkBout$2.act(FkBout.java:89)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
    at com.netbout.rest.bout.FkBout.route(FkBout.java:81)
    at com.netbout.rest.bout.FkBout.access$000(FkBout.java:52)
    at com.netbout.rest.bout.FkBout$1.route(FkBout.java:65)
    at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
    at org.takes.facets.fork.TkFork.act(TkFork.java:99)
    at org.takes.tk.TkWrap.act(TkWrap.java:59)
    at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
    at org.takes.facets.fork.TkFork.act(TkFork.java:99)
    at com.netbout.rest.FkRegistered$1.route(FkRegistered.java:70)
    at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
    at org.takes.facets.fork.TkFork.act(TkFork.java:99)
    at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
    at org.takes.facets.fork.TkFork.act(TkFork.java:99)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:107)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:87)
    at org.takes.tk.TkWrap.act(TkWrap.java:59)
    at org.takes.facets.forward.TkForward.act(TkForward.java:66)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:78)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:48)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:60)
    at org.takes.tk.TkWrap.act(TkWrap.java:59)
    at org.takes.tk.TkWrap.act(TkWrap.java:59)
    at org.takes.facets.flash.TkFlash.act(TkFlash.java:98)
    at org.takes.tk.TkMeasured$1.act(TkMeasured.java:65)
    at org.takes.tk.TkWrap.act(TkWrap.java:59)
    at org.takes.tk.TkVersioned$1.act(TkVersioned.java:70)
    at org.takes.tk.TkWrap.act(TkWrap.java:59)
    at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:69)
    at org.takes.tk.TkWrap.act(TkWrap.java:59)
    at org.takes.tk.TkWrap.act(TkWrap.java:59)
    at org.takes.http.BkBasic.print(BkBasic.java:99)
    at org.takes.http.BkBasic.accept(BkBasic.java:77)
    at org.takes.http.BkSafe.accept(BkSafe.java:58)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
    at org.takes.http.BkParallel$1.run(BkParallel.java:97)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

I am using `Google Chrome Version 47.0.2526.8 dev-m (64-bit)`.

**Comment by dmzaytsev** [comment]
@Rossiar just curious why do you need such strange bout's name?
anyway thanks for reporting

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@rossiar I set milestone here to `3.1`, let me know if it is wrong

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev thanks, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev I will ask somebody else to pick this up
