### ISSUE TITLE
Facebook login doesn't work

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#820]
I tried login via facebook and got stack trace

![image](https://cloud.githubusercontent.com/assets/9972909/10615299/768d3d10-7778-11e5-91cc-20f1f253e207.png)

>java.lang.NoSuchFieldError: LATEST
	at org.takes.facets.auth.social.PsFacebook.fetch(PsFacebook.java:165)
	at org.takes.facets.auth.social.PsFacebook.enter(PsFacebook.java:131)
	at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:108)
	at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
	at com.netbout.rest.PsTwice.enter(PsTwice.java:70)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:86)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:80)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:50)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:62)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:106)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

let's fix it

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@dmzaytsev there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@dmzaytsev thanks for the report, I topped your acc for 30 mins, payment ID `67821520`

**Comment by dmzaytsev** [comment]
@karato please assign this to @bdragan

**Comment by karato** [comment]
> @karato please assign this to @bdragan 

@dmzaytsev yep, done. @bdragan it is your task now

**Comment by dmzaytsev** [comment]
@bdragan thanks!

**Comment by karato** [comment]
@bdragan there weren't any messages from you, no need to pay, as I understand (feel free to correct me)

**Comment by bdragan** [comment]
@karato PR #824 has been merged to master. The issue has been fixed and reviewed. I expected quality review to be completed before I start complaining about the payment. :)

Please, could you send me a link to any docs about the task resolution workflow we follow? I found [How XDSD Is Different](http://www.yegor256.com/2014/04/17/how-xdsd-is-different.html) and [Definition Of Done](http://www.yegor256.com/2014/04/15/definition-of-done.html), but none of them seem to cover the details about the steps that the issue goes through between the PR merge and the payment.

Thanks! :)

**Comment by dmzaytsev** [comment]
@bdragan please check the quality rules http://www.teamed.io/qa.html

> Some of ticket messages must mention all pull requests where the problem was actually fixed.

but @karato uses some automatic tools to check tickets that's why got this warning before QA review

The policy http://www.teamed.io/policy.html will be useful too.

anyway when you complete the task (PR or PRs merged) ask the ticket reporter to close the ticket and mention PR which fixed the issue.

**Comment by bdragan** [comment]
@dmzaytsev Thank you for the explanation!

**Comment by yegor256** [comment]
@karato pls add extra 30 mins to @bdragan

**Comment by karato** [comment]
> @karato pls add extra 30 mins to @bdragan 

@yegor256 30 mins extra was just paid to @bdragan, transaction `68413110`
