### ISSUE TITLE
NoSuchElementException: no more items in the frame, position=-1 strikes back

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#834]
Requested url:
``` http://www.netbout.com/b/36037 ```
Stracktrace:
```
java.util.NoSuchElementException: no more items in the frame, position=-1
	at com.jcabi.dynamo.AwsIterator.next_aroundBody2(AwsIterator.java:162)
	at com.jcabi.dynamo.AwsIterator$AjcClosure3.run(AwsIterator.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.AwsIterator.next(AwsIterator.java:160)
	at com.jcabi.dynamo.AwsIterator.next(AwsIterator.java:62)
	at com.jcabi.dynamo.retry.ReIterator.next_aroundBody4(ReIterator.java:78)
	at com.jcabi.dynamo.retry.ReIterator$AjcClosure5.run(ReIterator.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.retry.ReIterator.next_aroundBody6(ReIterator.java:78)
	at com.jcabi.dynamo.retry.ReIterator$AjcClosure7.run(ReIterator.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:82)
	at com.jcabi.dynamo.retry.ReIterator.next(ReIterator.java:78)
	at com.netbout.dynamo.DyMessages.unread_aroundBody2(DyMessages.java:196)
	at com.netbout.dynamo.DyMessages$AjcClosure3.run(DyMessages.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.dynamo.DyMessages.unread(DyMessages.java:196)
	at com.netbout.cached.CdMessages$Flag.unread_aroundBody0(CdMessages.java:145)
	at com.netbout.cached.CdMessages$Flag$AjcClosure1.run(CdMessages.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:302)
	at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:147)
	at com.netbout.cached.CdMessages$Flag.unread(CdMessages.java:145)
	at com.netbout.cached.CdMessages.unread_aroundBody2(CdMessages.java:83)
	at com.netbout.cached.CdMessages$AjcClosure3.run(CdMessages.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.cached.CdMessages.unread(CdMessages.java:83)
	at com.netbout.email.EmMessages.unread_aroundBody2(EmMessages.java:127)
	at com.netbout.email.EmMessages$AjcClosure3.run(EmMessages.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.email.EmMessages.unread(EmMessages.java:127)
	at com.netbout.rest.bout.TkIndex.act(TkIndex.java:82)
	at com.netbout.rest.bout.FkBout$3.act(FkBout.java:111)
	at com.netbout.rest.bout.FkBout$2.act(FkBout.java:89)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at com.netbout.rest.bout.FkBout.route(FkBout.java:81)
	at com.netbout.rest.bout.FkBout.access$000(FkBout.java:52)
	at com.netbout.rest.bout.FkBout$1.route(FkBout.java:65)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at com.netbout.rest.FkRegistered$1.route(FkRegistered.java:70)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:80)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:50)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:62)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:100)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dmzaytsev** [comment]
@longtimeago is the issue stable?

**Comment by longtimeago** [comment]
@dmzaytsev yes, I'm still observing it

**Comment by dmzaytsev** [comment]
@longtimeago well I guess it is a data specific problem in your bout. I can't reproduce it locally or remote.
But I can try to make a quick fix. I hope it will help

**Comment by dmzaytsev** [comment]
@karato it is a valid bug

**Comment by longtimeago** [comment]
@dmzaytsev I think that's because I requested a bout, which does not exist anymore (closed/deleted)

**Comment by dmzaytsev** [comment]
@longtimeago oh it helpful, thanks!
but just curious why you need access to the not existing bout? : )

Could you let me know the steps to reproduce it if possible?
As I know netbout doesn't allow to delete a bout

**Comment by karato** [comment]
> @karato it is a valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by longtimeago** [comment]
@dmzaytsev I've discovered that during the interview.
When I reject the applicant Alice removes that bout somehow. At least it disappears from the list of my bouts.
But if the bout is still openned in my browser and I refresh the page I get this error.

**Comment by dmzaytsev** [comment]
@longtimeago it's more clear now, thanks

**Comment by karato** [comment]
@longtimeago I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@longtimeago thanks for the report, I topped your acc for 15 mins, payment ID `69590833`

**Comment by karato** [comment]
@2686747 This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here; **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by 2686747** [comment]
@karato @dmzaytsev it depends on #1085 which has a problem with caching. I can propose 3 solutions: 
- wait for #1085 resolving, it will fix this (and similar) issue
- just catch exception - seems like fix of result but not a reason and similar issue can become
- remove cache annotations from some methods - if cache isn't really necessary will work
waiting #1085 now

**Comment by karato** [comment]
> @karato @dmzaytsev it depends on #1085 which has a problem with caching. I can propose 3 solutions: 
> - wait for #1085 resolving, it will fix this (and similar) issue
> - just catch exception - seems like fix of result but not a reason and similar issue can become
> - remove cache annotations from some methods - if cache isn't really necessary will work
> 
> waiting #1085 now

@2686747 try to address your comments to one person, to avoid noise, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by 2686747** [comment]
@karato waiting #1085

**Comment by karato** [comment]
@2686747 15 days already, in 48 hours I will re-assign

-30 to your rating, your total score is [+61](http://www.netbout.com/b/36452?open=rating)

**Comment by 2686747** [comment]
> @karato waiting #1085

@karato i asked you for waiting  resolving #1085, i can't do normally this task without rejection/confirmation this bug.

**Comment by dmzaytsev** [comment]
@2686747 just catch the exception to get proper error message instead of a stack trace

**Comment by karato** [comment]
> @karato waiting #1085

@2686747 ok, let's wait for #1085

**Comment by karato** [comment]
@longtimeago impediment in issue #1085 is closed, we can probably try to continue here

**Comment by 2686747** [comment]
@dmzaytsev please, check #1094

**Comment by original-brownbear** [comment]
@longtimeago I was only CR here, but seems the performer forgot to ask you to close here and I'm already at 17 open tasks :) Fix should be fine ;)

**Comment by longtimeago** [comment]
@original-brownbear nice, thanks :)

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka many thanks

**Comment by karato** [comment]
@2686747 paied 10 mins to @ypshenychka for QA review (payment ID is `82131999`). Thanks a lot, I just topped your account for **30 mins**, transaction ID `56fe8add2e23293e8600026f`, total time was 138 hours and 41 mins. +30 to your rating, your total score is [+91](http://www.netbout.com/b/36452?open=rating)
