### ISSUE TITLE
Build fails on Windows during 'bower install' phase when frontend-maven-plugin is executed

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#849]
Error occurs every time I invoke `mvn clean install` from console on Windows 10 when `netbout-web` project is build. It happens during `bower install` phase of frontend-maven-plugin execution.

Logs:
```
[INFO] --- frontend-maven-plugin:0.0.25:install-node-and-npm (install node and npm) @ netbout-web ---
[INFO] Node v0.12.7 is already installed.
[INFO] Found NPM version 2.11.3
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.25:npm (npm install) @ netbout-web ---
[INFO] Running 'npm install bower --color=false' in C:\IdeaProjects\netbout\netbout-web
[INFO] bower@1.7.0 node_modules\bower
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.25:bower (bower install) @ netbout-web ---
[INFO] Running 'bower install' in C:\IdeaProjects\netbout\netbout-web
[INFO] bower jquery-textcomplete#~0.7.3           cached git://github.com/yuku-t/jquery-textcomplete.git#0.7.3
[INFO] bower jquery-textcomplete#~0.7.3         validate 0.7.3 against git://github.com/yuku-t/jquery-textcomplete.git#~0.7.3
[INFO] bower jquery#>=1.7.0                       cached git://github.com/jquery/jquery.git#2.1.4
[INFO] bower jquery#>=1.7.0                     validate 2.1.4 against git://github.com/jquery/jquery.git#>=1.7.0
[INFO] bower jquery-textcomplete#~0.7.3          install jquery-textcomplete#0.7.3
[INFO] bower jquery#>=1.7.0                      install jquery#2.1.4
[INFO] bower                                 postinstall sh src/main/bower/postinstall.sh
[ERROR] bower                                      ENOENT spawn sh ENOENT
[ERROR] 
[ERROR] Stack trace:
[ERROR] Error: spawn sh ENOENT
[ERROR]     at exports._errnoException (util.js:746:11)
[ERROR]     at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
[ERROR]     at child_process.js:1144:20
[ERROR]     at process._tickCallback (node.js:355:11)
[ERROR] 
[ERROR] Console trace:
[ERROR] Error
[ERROR]     at StandardRenderer.error (C:\IdeaProjects\netbout\netbout-web\node_modules\bower\lib\renderers\StandardRenderer.js:82:37)
[ERROR]     at Logger.<anonymous> (C:\IdeaProjects\netbout\netbout-web\node_modules\bower\bin\bower:110:22)
[ERROR]     at Logger.emit (events.js:107:17)
[ERROR]     at Logger.emit (C:\IdeaProjects\netbout\netbout-web\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
[ERROR]     at C:\IdeaProjects\netbout\netbout-web\node_modules\bower\lib\commands\index.js:68:20
[ERROR]     at _rejected (C:\IdeaProjects\netbout\netbout-web\node_modules\bower\node_modules\q\q.js:844:24)
[ERROR]     at C:\IdeaProjects\netbout\netbout-web\node_modules\bower\node_modules\q\q.js:870:30
[ERROR]     at Promise.when (C:\IdeaProjects\netbout\netbout-web\node_modules\bower\node_modules\q\q.js:1122:31)
[ERROR]     at Promise.promise.promiseDispatch (C:\IdeaProjects\netbout\netbout-web\node_modules\bower\node_modules\q\q.js:788:41)
[ERROR]     at C:\IdeaProjects\netbout\netbout-web\node_modules\bower\node_modules\q\q.js:604:44
[ERROR] System info:
[ERROR] Bower version: 1.7.0
[ERROR] Node version: 0.12.7
[ERROR] OS: Windows_NT 6.3.9600 x64
```

**Comment by dmzaytsev** [comment]
@mkordas I just built it on Windows 10 
![image](https://cloud.githubusercontent.com/assets/9972909/11720394/d06ee0f6-9f80-11e5-9d43-5b89a9b9dbd2.png)

how a ticket performer can reproduce the issue?
If you have any idea, please let me know

**Comment by mkordas** [comment]
@dmzaytsev Thanks for confirmation that it works for you - it's not about system then. I'll reopen this issue whenever I'll have reliable reproducer.

**Comment by ivanjunckes** [comment]
@mkordas I am having this issue while trying to setup my local env. Can anyone help me out?

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building netbout-web 3.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ netbout-web ---
[INFO] Deleting D:\Documents\Teamed\workspace\netbout\netbout-web\target
[INFO]
[INFO] --- maven-dependency-plugin:2.8:unpack (unpack-dynamodb-local) @ netbout-web ---
[INFO] Configured Artifact: com.jcabi:DynamoDBLocal:2014-01-08:zip
[INFO] Unpacking C:\Users\Ivan\.m2\repository\com\jcabi\DynamoDBLocal\2014-01-08\DynamoDBLocal-2014-01-08.zip to D:\Documents\Teamed\workspace\netbout\netbout-web\target\dynamodb-dist with includes "" and excludes ""
[INFO]
[INFO] --- buildnumber-maven-plugin:1.3:create (jcabi-build-number) @ netbout-web ---
[INFO] ShortRevision tag detected. The value is '7'.
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify --short=7 HEAD"
[INFO] Working directory: D:\Documents\Teamed\workspace\netbout\netbout-web
[INFO] Storing buildNumber: e6472f5 at timestamp: 2015-12-12T16:38:38
[INFO] Storing buildScmBranch: master
[INFO]
[INFO] --- buildnumber-maven-plugin:1.3:create-timestamp (jcabi-build-number) @ netbout-web ---
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:install-node-and-npm (install node and npm) @ netbout-web ---
[INFO] Node v0.12.7 is already installed.
[INFO] Found NPM version 2.11.3
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:npm (npm install) @ netbout-web ---
[INFO] Running 'npm install bower --color=false' in D:\Documents\Teamed\workspace\netbout\netbout-web
[INFO] bower@1.7.1 node_modules\bower
[INFO] ΓööΓöÇΓöÇ semver-utils@1.1.1
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:bower (bower install) @ netbout-web ---
[INFO] Running 'bower install' in D:\Documents\Teamed\workspace\netbout\netbout-web
[INFO] bower jquery-textcomplete#~0.7.3           cached git://github.com/yuku-t/jquery-textcomplete.git#0.7.3
[INFO] bower jquery-textcomplete#~0.7.3         validate 0.7.3 against git://github.com/yuku-t/jquery-textcomplete.git#~0.7.3
[INFO] bower jquery#>=1.7.0                       cached git://github.com/jquery/jquery.git#2.1.4
[INFO] bower jquery#>=1.7.0                     validate 2.1.4 against git://github.com/jquery/jquery.git#>=1.7.0
[INFO] bower jquery-textcomplete#~0.7.3          install jquery-textcomplete#0.7.3
[INFO] bower jquery#>=1.7.0                      install jquery#2.1.4
[INFO] bower                                 postinstall sh src/main/bower/postinstall.sh
[ERROR] bower                                      ENOENT spawn sh ENOENT
[ERROR]
[ERROR] Stack trace:
[ERROR] Error: spawn sh ENOENT
[ERROR]     at exports._errnoException (util.js:746:11)
[ERROR]     at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
[ERROR]     at child_process.js:1144:20
[ERROR]     at process._tickCallback (node.js:355:11)
[ERROR]
[ERROR] Console trace:
[ERROR] Error
[ERROR]     at StandardRenderer.error (D:\Documents\Teamed\workspace\netbout\netbout-web\node_modules\bower\lib\renderers\StandardRenderer.js:83:37)
[ERROR]     at Logger.<anonymous> (D:\Documents\Teamed\workspace\netbout\netbout-web\node_modules\bower\bin\bower:116:30)
[ERROR]     at Logger.emit (events.js:107:17)
[ERROR]     at Logger.emit (D:\Documents\Teamed\workspace\netbout\netbout-web\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
[ERROR]     at D:\Documents\Teamed\workspace\netbout\netbout-web\node_modules\bower\lib\commands\index.js:48:20
[ERROR]     at _rejected (D:\Documents\Teamed\workspace\netbout\netbout-web\node_modules\bower\node_modules\q\q.js:844:24)
[ERROR]     at D:\Documents\Teamed\workspace\netbout\netbout-web\node_modules\bower\node_modules\q\q.js:870:30
[ERROR]     at Promise.when (D:\Documents\Teamed\workspace\netbout\netbout-web\node_modules\bower\node_modules\q\q.js:1122:31)
[ERROR]     at Promise.promise.promiseDispatch (D:\Documents\Teamed\workspace\netbout\netbout-web\node_modules\bower\node_modules\q\q.js:788:41)
[ERROR]     at D:\Documents\Teamed\workspace\netbout\netbout-web\node_modules\bower\node_modules\q\q.js:604:44
[ERROR] System info:
[ERROR] Bower version: 1.7.1
[ERROR] Node version: 0.12.7
[ERROR] OS: Windows_NT 6.3.9600 x64
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:23 min
[INFO] Finished at: 2015-12-12T16:39:46-02:00
[INFO] Final Memory: 25M/223M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:bower (bower install) on project netbout-web: Failed to run task: 'bower install' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by mkordas** [comment]
@ivanjunckes so we have exactly the same issue. What Maven version do you use?

**Comment by ivanjunckes** [comment]
```
D:\Documents\Teamed\workspace\netbout\netbout-web>mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T14:41:47-02:00)
Maven home: C:\apache-maven-3.3.9\bin\..
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_79\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "windows"
```

**Comment by mkordas** [comment]
Here are my details:
```
C:\IdeaProjects\netbout>mvn -v
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: C:\Program Files\Apache\apache-maven-3.2.5
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_25\jre
Default locale: en_US, platform encoding: Cp1250
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "dos"
```
So failure happens both on JDK 7/JDK 8 and Maven 3.2.5/3.3.9.

@dmzaytsev can you share your environment details?

**Comment by mkordas** [comment]
@ivanjunckes I may have some trace. What is your `PATHEXT` env variable? When I change it from `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC` to default `.COM;.EXE;.BAT;.CMD` this error disappears (but I get another one).

**Comment by ivanjunckes** [comment]
@mkordas I changed it to ```.COM;.EXE;.BAT;.CMD``` but keep getting the same error.

**Comment by dmzaytsev** [comment]
@mkordas 
```
C:\>mvn -v
Picked up JAVA_TOOL_OPTIONS: -Duser.country=US -Duser.language=en  -Dfile.encoding=UTF8
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T16:57:37+05:00)
Maven home: C:\utils\apache-maven-3.3.3\bin\..
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: C:\utils\jdk1.7.0_80\jre
Default locale: en_US, platform encoding: UTF8
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "windows"
```

**Comment by ivanjunckes** [comment]
@mkordas I found a way to fix it, but not sure if this is the best solution. 
I changed this file ```..\netbout\netbout-web\.bowerrc``` removing ```sh src/main/bower/postinstall.sh``` from the ```postinstall``` property, thus it will avoid the execution of the sh script. Bash scripts are not supposed to be executed on windows, so it ends up failing.
```
{
  "directory": "target/js-tmp",
  "scripts": {
	  "postinstall": ""
	}
}
```
@dmzaytsev can you share your .bowerrc configuration?

**Comment by dmzaytsev** [comment]
@ivanjunckes does it make sense to share `.bowerrc`? it always pulls from github
but It seems I realized what's the matter

```
C:\>sh --version
GNU bash, version 3.1.23(6)-release (i686-pc-msys)
Copyright (C) 2005 Free Software Foundation, Inc.
```

@mkordas if you reopened the issue I will put a bug tag here

**Comment by mkordas** [comment]
@dmzaytsev I've reopened the issue

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by ivanjunckes** [comment]
@dmzaytsev I was just wondering if you did local changes to make it work :)

I installed bash for windows and it is working properly, we may need to add instructions to install bash.

**Comment by dmzaytsev** [comment]
@ivanjunckes yeah, README needs to be updated or maybe it needs to make some modifications in `.bowerrc`
I don't know exactly

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@mkordas since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@mkordas thanks for the ticket, your account was topped for 15 mins, payment 566ed847d26ede56550002dc

**Comment by karato** [comment]
@2686747 this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions

Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by 2686747** [comment]
@mkordas Project uses bower, so : "_Bower depends on Node.js and npm. Also make sure that git is installed as some bower packages require it to be fetched and installed._" ([details](https://github.com/bower/bower)). Also please see #993. As result i see two solutions: 
1. edit our documentation
2. do over script editing job for windows users for installing full bower dependencies
What do you think about it?

**Comment by mkordas** [comment]
@2686747 I think our architect should make decision here

**Comment by dmzaytsev** [comment]
@2686747 @mkordas I think we should mention in readme about git for window as requirements  for windows users
(or git and sh.exe)

**Comment by mkordas** [comment]
@dmzaytsev @2686747 fine with me, but I would be precise - let's write that `sh.exe` should be in `PATH`

**Comment by 2686747** [comment]
@dmzaytsev More investigations: bower's [postinstall.sh](https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/bower/postinstall.sh) script is too OS dependent for simple copy/rm operations (the reason of windows fails here). i think i have to rewrite this on something more independable here (node.js, e.g.) or invoke this from maven.

**Comment by dmzaytsev** [comment]
@2686747 @mkordas by the way Git for windows contains mv and rm and other utilities
we need `sh.exe` as requirement
I guess we already have `mv.exe` and others

@2686747 anyway you can rewrite the script or invoke copy operation from maven
it's up to you

**Comment by 2686747** [comment]
@dmzaytsev check, please, #1073

**Comment by karato** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks a lot

**Comment by karato** [comment]
@2686747 paied 10 mins to @elenavolokhova for QA review (payment ID is `79793533`); **38 mins** sent to your balance (ID `56df0bd38c97370250000217`), many thanks! It took 67 hours and 13 mins.; m=4033, that's why a bonus here for fast delivery; +38 added to your rating, at the moment it is: [+16](http://www.netbout.com/b/36452?open=rating)

**Comment by 2686747** [comment]
@karato Thanks a lot

**Comment by karato** [comment]
> @karato Thanks a lot
> 
> 

@2686747 sure, you are welcome
