### ISSUE TITLE
Error when starting server with '-DskipTests'

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#851]
When command `mvn install -DskipTests  -Phit-refresh -Dport=8080` is invoked on Windows, the following exception crashes the build:
```
[INFO] --- exec-maven-plugin:1.3:java (start-server) @ netbout-web ---
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3:java (start-server) on project netbout-web: An exception occured while executing the Java class. null: InvocationTargetException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3:java (start-server) on project netbout-web: An exception occured while executing the Java class. null
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occured while executing the Java class. null
        at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:345)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.netbout.dynamo.DyBase.<init>(DyBase.java:71)
        at com.netbout.Launch.main(Launch.java:62)
        ... 6 more
```

**Comment by dmzaytsev** [comment]
@mkordas you skip tests and that's why local DynamoDB doesn't start

Readme [says](https://github.com/yegor256/netbout#run-locally-and-test-it)
```
$ mvn clean install -Phit-refresh -Dport=8080
```

**Comment by mkordas** [comment]
I used `-DskipTests` because I was blocked by #850. This is pretty standard Maven property that is even available as a button e.g. in IntelliJ. We shouldn't fail the build with totally not meaningful `NumberFormatException: null` just because someone doesn't want to invoke tests before running the application.

**Comment by mkordas** [comment]
@dmzaytsev please dispatch this issue

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@mkordas attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@mkordas many thanks for the bug report, I added 15 mins to your acc, transaction `56af449895ff72796e00040e`

**Comment by karato** [comment]
@original-brownbear this is your task

**Comment by original-brownbear** [comment]
@mkordas PR #1068 created, now runs locally without forcing you to run tests before :)

**Comment by original-brownbear** [comment]
@mkordas as always: close please given this is merged :) thanks!

**Comment by mkordas** [comment]
@original-brownbear thanks!

**Comment by original-brownbear** [comment]
@karato please pay attention to this ticket as well as my other closed tickets in your project. I closed all of them in a very short period of time each, still I'm blocked by having them pile up as open tasks and receive an unrealistic speed rating by them staying open long after the PRs are closed and payment on them is handled.
Thanks :)

**Comment by karato** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks a lot :)

**Comment by karato** [comment]
@original-brownbear paied 10 mins to @ypshenychka for QA review (payment ID is `79318454`)

**1 hour** was added to your account, many thanks for your contribution (payment AP-2JL00201N5175423T)! The task took 23 hours and 31 mins.

the bonus for fast delivery (m=1411)

+60 added to your rating, at the moment it is: [+692](http://www.netbout.com/b/36646?open=rating)
