### ISSUE TITLE
Setting bout name to empty string causes not handled exception

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#862]
1. Go to www.netbout.com/start
2. Click name of bout ("untitled") and remove all characters (make name empty)
3. Press enter

Application crashes with the following stacktrace:
```
java.lang.IllegalArgumentException: bout title can't be empty
	at com.netbout.dynamo.DyBout.rename_aroundBody8(DyBout.java:116)
	at com.netbout.dynamo.DyBout$AjcClosure9.run(DyBout.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.dynamo.DyBout.rename(DyBout.java:115)
	at com.netbout.cached.CdBout.rename_aroundBody14(CdBout.java:96)
	at com.netbout.cached.CdBout$AjcClosure15.run(CdBout.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.cached.CdBout.rename(CdBout.java:96)
	at com.netbout.email.EmBout.rename_aroundBody8(EmBout.java:104)
	at com.netbout.email.EmBout$AjcClosure9.run(EmBout.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.email.EmBout.rename(EmBout.java:104)
	at com.netbout.rest.bout.TkRename.act(TkRename.java:70)
	at com.netbout.rest.bout.FkBout$3.act(FkBout.java:111)
	at com.netbout.rest.bout.FkBout$2.act(FkBout.java:89)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at com.netbout.rest.bout.FkBout.route(FkBout.java:97)
	at com.netbout.rest.bout.FkBout.access$000(FkBout.java:52)
	at com.netbout.rest.bout.FkBout$1.route(FkBout.java:65)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at com.netbout.rest.FkRegistered$1.route(FkRegistered.java:70)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:80)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:50)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:62)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:100)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.FtCLI$1.act(FtCLI.java:84)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@mkordas I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@mkordas thank you for reporting this, I added 15 mins to your acc, transaction `566c8bc8de472f4f2a000103`

**Comment by karato** [comment]
@carlosgines This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here

Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by CarlosGines** [comment]
Thank you @karato I will get down to it very soon. I will ask if I have any question.

**Comment by CarlosGines** [comment]
@karato I have a question. I have been reading a lot about how we work with tasks, please let me know if what I have concluded is right. The workflow should be like this:

- I fork the main repo and create a local clone of my fork.
- I fix the bug in master in my fork.
- Run Maven build with Qulice to check everything is alright.
- Commit my changes and create a Pull Request.
- Post a link to the PR here.
- I am done, I am not in charge of invoking Rultor to merge.

Is it right?

**Comment by dmzaytsev** [comment]
@CarlosGines 
>I fork the main repo and create a local clone of my fork.

right
>I fix the bug in master in my fork.

it would better to create a new branch for each issue. That allows work on more than one issue at the same time

> Run Maven build with Qulice to check everything is alright.

right

> Commit my changes and create a Pull Request.

commit and push your changes and create a pull request

> Post a link to the PR here.

right 

> I am done, I am not in charge of invoking Rultor to merge

the pull request will be assigned to the code review. 
the reviewer should accept the pull request before your work will be complete

**Comment by CarlosGines** [comment]
@dmzaytsev Thank you. Another question, do you have any document that explains the architecture of the project? I think it is important for new developers. I also see you are using at least "jcabi" and "takes" project within this one (which are new to me too). Any explanation on how all of this works together?

**Comment by dmzaytsev** [comment]
@CarlosGines there is only one document. It's Readme on each project

**Comment by CarlosGines** [comment]
I have created issue #1033 that needs to be addressed before I can continue with this task. Waiting for its approval.

**Comment by CarlosGines** [comment]
@karato How does my last message affect my "timer" for this task? Is it stopped? Is it stopped only if the issue is accepted? In that last case, would it be stopped from the moment it is accepted or from the moment I posted it? Thank you.

**Comment by karato** [comment]
> @karato How does my last message affect my "timer" for this task? Is it stopped? Is it stopped only if the issue is accepted? In that last case, would it be stopped from the moment it is accepted or from the moment I posted it? Thank you.

@carlosgines every time you post a message, address it to someone. otherwise it's just a noise. see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noise-mdash-address-your-comments

**Comment by CarlosGines** [comment]
Ok @karato I will keep it in mind. Please check PR #1050 for this task. I still consider issue #1033 above relevant, but I have managed anyways.

**Comment by CarlosGines** [comment]
@mkordas bug fixed in PR #1050 Please close the ticket.

**Comment by mkordas** [comment]
@CarlosGines thanks

**Comment by karato** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@CarlosGines 
> CarlosGines commented 6 days ago
I have created issue #1033 that needs to be addressed before I can continue with this task. Waiting for its approval.

 According to our [quality rules](http://www.teamed.io/qa.html):
 > Messages in a ticket always start with a name of a user they are addressed to.
 
 As far as you are the performer of this ticket you are responsible for its quality. Please follow this rule in your tickets in the future. All issues should be fixed before ticket is closed and passed to QA. In this case you should have fixed your comment.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by CarlosGines** [comment]
@elenavolokhova everything is clear and I have no questions regarding this approach. I have fixed my comment here too. Thank you.

**Comment by elenavolokhova** [comment]
@CarlosGines Thank you!

**Comment by elenavolokhova** [comment]
@karato Quality is acceptable here.

**Comment by karato** [comment]
> @karato Quality is acceptable here.

@elenavolokhova thanks, got it. everybody, please try to make it good next time

**Comment by CarlosGines** [comment]
@karato sure, I have learnt a lot from this, my first ticket, I will keep improving.

**Comment by karato** [comment]
@carlosgines 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 79078243. thank you, added **30 mins** to your acc, payment num is `AP-82B510046B4381619`, 158 hours and 57 mins spent in total to complete. added +30 to your rating, now it is equal to [+30](http://www.netbout.com/b/36645?open=rating)
