### ISSUE TITLE
Trying to invite alias with long string causes not handled exception

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#864]
1. Go to www.netbout.com/start
2. Paste into `Invite...` field some longer string, for example `123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890`
3. Press enter
Application crashes with the following stacktrace:
```
java.lang.IllegalArgumentException: alias is too long
	at com.netbout.dynamo.DyFriends.clean(DyFriends.java:207)
	at com.netbout.dynamo.DyFriends.invite_aroundBody0(DyFriends.java:129)
	at com.netbout.dynamo.DyFriends$AjcClosure1.run(DyFriends.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.dynamo.DyFriends.invite(DyFriends.java:129)
	at com.netbout.cached.CdFriends.invite_aroundBody0(CdFriends.java:72)
	at com.netbout.cached.CdFriends$AjcClosure1.run(CdFriends.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.cached.CdFriends.invite(CdFriends.java:72)
	at com.netbout.email.EmFriends.invite_aroundBody0(EmFriends.java:65)
	at com.netbout.email.EmFriends$AjcClosure1.run(EmFriends.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.email.EmFriends.invite(EmFriends.java:65)
	at com.netbout.rest.bout.TkInvite.act(TkInvite.java:99)
	at com.netbout.rest.bout.FkBout$3.act(FkBout.java:111)
	at com.netbout.rest.bout.FkBout$2.act(FkBout.java:89)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at com.netbout.rest.bout.FkBout.route(FkBout.java:81)
	at com.netbout.rest.bout.FkBout.access$000(FkBout.java:52)
	at com.netbout.rest.bout.FkBout$1.route(FkBout.java:65)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at com.netbout.rest.FkRegistered$1.route(FkRegistered.java:70)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:80)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:50)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:62)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:100)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
I would expect just an error message that alias name is too long.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@mkordas I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
@mkordas thanks for tis bug, I topped your account for 15 mins, transaction `566d4ce29ee017247d000298`

**Comment by karato** [comment]
@kitsook this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by kitsook** [comment]
@dmzaytsev i can reproduce it on the production site but not localhost. test environment handles `RsFailure` differently?

**Comment by dmzaytsev** [comment]
@kitsook i'm not sure. Maybe it fixed already with another issue...
I would suggest checkout latest release and check against the local instance again

**Comment by dmzaytsev** [comment]
@kitsook try http://snapshot.netbout.com first

**Comment by kitsook** [comment]
@dmzaytsev sorry that i wasn't clear in my question.  i can trigger an uncaught exception on localhost if the alias is too long.  if i modified the code to throw a proper `RsFailure`, the stacktrace is gone but I can't get the `flash` tag in the result xml.

i tried to invite an unknown alias, which should show `incorrect alias "xxxxxxx", try again`.  but i can't get this either on localhost.

so i am wondering if the test environment is configured differently

**Comment by dmzaytsev** [comment]
@kitsook I don't know why it happens...
let's add a unit test with expected RsFaulure exception

**Comment by kitsook** [comment]
@karato please assign to someone else

**Comment by karato** [comment]
> @karato please assign to someone else

@kitsook -30 points to your rating

**Comment by karato** [comment]
> @karato please assign to someone else

@kitsook all right, we'll find someone else for this task

**Comment by karato** [comment]
@jhyle the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by jhyle** [comment]
@karato please have a look at PR #984

**Comment by karato** [comment]
> @karato please have a look at PR #984

@jhyle thank you

**Comment by karato** [comment]
@jhyle 15 days already, in 48 hours I will re-assign; -30 added to your rating, at the moment it is: [+75](http://www.netbout.com/b/36320?open=rating)

**Comment by jhyle** [comment]
@karato ??? It's merged, what did I do wrong?

**Comment by dmzaytsev** [comment]
@jhyle you have to ask the ticket reporter to close the ticket

**Comment by jhyle** [comment]
@mkordas Please close the ticket.

**Comment by mkordas** [comment]
@jhyle thanks

**Comment by karato** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka many thanks

**Comment by karato** [comment]
@jhyle I added 10 mins to @ypshenychka (for QA review) in transaction 77636322; Thanks so much! Your account was topped up for **30 mins** (transaction ID is `AP-2D7062835D7017110`, the task took 387 hours and 51 mins); +30 added to your rating, current score is: [+105](http://www.netbout.com/b/36320?open=rating)
