### ISSUE TITLE
broken test TkAttachTest#sendsMessageToBout() on windows

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#868]
We have a broken test TkAttachTest#sendsMessageToBout() on windows
`mvn clean install` causes the stack trace like below

>Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.503 sec <<< FAILURE! - in com.netbout.rest.bout.TkAttachTest
sendsMessageToBout(com.netbout.rest.bout.TkAttachTest)  Time elapsed: 1.465 sec  <<< ERROR!
java.io.IOException: Unable to delete file: C:\Users\Dmitry\AppData\Local\Temp\netbout8077744991897733500bin
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
        at com.netbout.rest.bout.TkAttach.act(TkAttach.java:124)
        at com.netbout.rest.bout.FkBout$3.act(FkBout.java:111)
        at com.netbout.rest.bout.FkBout$2.act(FkBout.java:89)
        at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
        at com.netbout.rest.bout.FkBout.route(FkBout.java:81)
        at com.netbout.rest.bout.FkBout.access$000(FkBout.java:52)
        at com.netbout.rest.bout.FkBout$1.route(FkBout.java:65)
        at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
        at com.netbout.rest.bout.TkAttachTest.sendsMessageToBout(TkAttachTest.java:95)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

I saw it on two Windows machines, Win 8 and Win 10

Let's fix it

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@dmzaytsev there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@dmzaytsev thanks for tis bug, I topped your account for 30 mins, transaction `71921211`

**Comment by exper0** [comment]
@dmzaytsev @karato ready to fix it - I encounter this bug as well

**Comment by dmzaytsev** [comment]
@karato assign @exper0 to this ticket please

**Comment by karato** [comment]
> @karato assign @exper0 to this ticket please

@dmzaytsev OK @exper0 please go ahead, this task is yours

**Comment by exper0** [comment]
@karato done

**Comment by dmzaytsev** [comment]
@exper0 to be paid you should ask a ticket reporter to close the ticket and mention the PR number  fixes the issue 
so you should ask me in this case

**Comment by exper0** [comment]
@dmzaytsev thanks for clarification. So if you are ok with my fix could you please close the ticket? PR 897

**Comment by dmzaytsev** [comment]
@exper0 PR number should be a link like `#897`

**Comment by exper0** [comment]
@dmzaytsev OK bug fixed in PR #897 Please close the ticket

**Comment by dmzaytsev** [comment]
@exper0 thanks!

**Comment by exper0** [comment]
@karato the issue is closed so I guess my account should be topped for 30mins?

**Comment by karato** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@elenavolokhova thank you :)

**Comment by karato** [comment]
@exper0 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 73337529; **1 hour** sent to your balance (ID `AP-5NL55921CM4167458`), many thanks! It took 18 hours and 48 mins.; the bonus for fast delivery (m=1128); +60 added to your rating, current score is: [+90](http://www.netbout.com/b/36185?open=rating)
