### ISSUE TITLE
Unexpected exception is thrown when kicking off user that is not in the bout

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#875]
To reproduce open any bout and add to URL string like `/kick?name=any`, e.g. `http://www.netbout.com/b/36163/kick?name=any`. It can also happen when user uses two windows for the same bout and tries to remove someone in both without refresh.

This is what is displayed:
![screenshot from 2015-12-17 00 44 01](https://cloud.githubusercontent.com/assets/5467276/11857330/89e3ac62-a457-11e5-8488-66abc1b19fa6.png)

Stacktrace:
```
com.netbout.spi.Friends$UnknownAliasException: alias 'any' is not in the bout
	at com.netbout.dynamo.DyFriends.kick_aroundBody2(DyFriends.java:155)
	at com.netbout.dynamo.DyFriends$AjcClosure3.run(DyFriends.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.dynamo.DyFriends.kick(DyFriends.java:148)
	at com.netbout.cached.CdFriends.kick_aroundBody2(CdFriends.java:78)
	at com.netbout.cached.CdFriends$AjcClosure3.run(CdFriends.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.cached.CdFriends.kick(CdFriends.java:78)
	at com.netbout.email.EmFriends.kick_aroundBody2(EmFriends.java:70)
	at com.netbout.email.EmFriends$AjcClosure3.run(EmFriends.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.email.EmFriends.kick(EmFriends.java:70)
	at com.netbout.rest.bout.TkKick.act(TkKick.java:70)
	at com.netbout.rest.bout.FkBout$3.act(FkBout.java:111)
	at com.netbout.rest.bout.FkBout$2.act(FkBout.java:89)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at com.netbout.rest.bout.FkBout.route(FkBout.java:81)
	at com.netbout.rest.bout.FkBout.access$000(FkBout.java:52)
	at com.netbout.rest.bout.FkBout$1.route(FkBout.java:65)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at com.netbout.rest.FkRegistered$1.route(FkRegistered.java:70)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:80)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:50)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:62)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:106)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

I would expect either no action at all or friendly message that user is not part of bout anymore.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@mkordas since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@mkordas thanks for the report, I topped your acc for 15 mins, payment ID `5672de9080c2b226890001c5`

**Comment by karato** [comment]
@michaelben this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here. **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by karato** [comment]
@michaelben check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

-30 added to your rating, current score is: [-75](http://www.netbout.com/b/36349?open=rating)

**Comment by karato** [comment]
@michaelben this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... added -60 to your rating, now it is equal to [-195](http://www.netbout.com/b/36349?open=rating)

**Comment by original-brownbear** [comment]
@karato I see this assigned to me in Netbout but not here, should I get on with it ?

**Comment by original-brownbear** [comment]
@karato put in PR #1031 , given that this counted towards my current task limit I hope this is ok :)

**Comment by karato** [comment]
@original-brownbear this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by original-brownbear** [comment]
@mkordas changes are merged now please close this :)

**Comment by mkordas** [comment]
@original-brownbear thanks!

**Comment by karato** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks for the review

**Comment by karato** [comment]
@original-brownbear added 10 mins to @elenavolokhova, for QA review, payment code is `78546734`; I just added **45 mins** to your account, many thanks for your contribution (AP-0HM44082TC269654J).. 43 hours and 48 mins spent here; there is a bonus for fast delivery (m=2628); +45 added to your rating, current score is: [+153](http://www.netbout.com/b/36646?open=rating)
