### ISSUE TITLE
Internal Application Error when path contains "[" or "]" character

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#877]
To reproduce put `[` or `]` at any place to path, e.g. go to `http://www.netbout.com/[` and see the following error:
![image](https://cloud.githubusercontent.com/assets/5467276/11864189/bce54560-a49a-11e5-8a6b-a73282154e0d.png)

Stacktrace:

```
java.lang.IllegalArgumentException: Illegal character in path at index 23: http://www.netbout.com/[
    at java.net.URI.create(URI.java:859)
    at org.takes.misc.Href.(Href.java:73)
    at org.takes.rq.RqHref$Base.href(RqHref.java:72)
    at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:101)
    at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
    at com.netbout.rest.PsTwice.enter(PsTwice.java:70)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:86)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.forward.TkForward.act(TkForward.java:68)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:80)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:50)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:62)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.flash.TkFlash.act(TkFlash.java:100)
    at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.http.BkBasic.print(BkBasic.java:99)
    at org.takes.http.BkBasic.accept(BkBasic.java:77)
    at org.takes.http.BkSafe.accept(BkSafe.java:58)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
    at org.takes.http.BkParallel$1.run(BkParallel.java:97)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Illegal character in path at index 23: http://www.netbout.com/[
    at java.net.URI$Parser.fail(URI.java:2829)
    at java.net.URI$Parser.checkChars(URI.java:3002)
    at java.net.URI$Parser.parseHierarchical(URI.java:3086)
    at java.net.URI$Parser.parse(URI.java:3034)
    at java.net.URI.(URI.java:595)
    at java.net.URI.create(URI.java:857)
    ... 29 more
```

I would expect redirect to home page without error or with information that path is invalid.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@mkordas since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@mkordas thanks for the ticket, your account was topped for 15 mins, payment 5672a80e9d6a2504300000a4

**Comment by karato** [comment]
@jhyle please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have; This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by jhyle** [comment]
@karato This should be fixed in the takes project. org.takes.misc.Href should catch the unchecked exception from URI.create in line 73 and rethrow it as a checked one so that programmers actually get informed that the method can fail. Then I a suggest a catch for this exception in org.takes.facets.auth.PsByFlag::enter. If the URI is not malformed it cannot match and so an empty Identity should be returned.

**Comment by karato** [comment]
> @karato This should be fixed in the takes project. org.takes.misc.Href should catch the unchecked exception from URI.create in line 73 and rethrow it as a checked one so that programmers actually get informed that the method can fail. Then I a suggest a catch for this exception in org.takes.facets.auth.PsByFlag::enter. If the URI is not malformed it cannot match and so an empty Identity should be returned.

@jhyle you should address your technical comments to the project architect (@dmzaytsev)

**Comment by dmzaytsev** [comment]
@jhyle feel free to submit a ticket on Takes project

**Comment by jhyle** [comment]
@dmzaytsev @karato See https://github.com/yegor256/takes/issues/548.

**Comment by jhyle** [comment]
@karato I have created the ticket. How to proceed?

**Comment by dmzaytsev** [comment]
@jhyle you should inform the program manager 

@karato we are waiting yegor256/takes#548

and just wait until yegor256/takes#548 will be resolved

**Comment by jhyle** [comment]
@karato Can you do something do move this forward?

**Comment by karato** [comment]
> @karato Can you do something do move this forward?

@jhyle what exactly do you want me to do? :)

**Comment by jhyle** [comment]
@karato Well, it seems like https://github.com/yegor256/takes/issues/548 is not getting reviewed (and filed as a bug). And what happens when the assignment hits the ten days mark?

**Comment by dmzaytsev** [comment]
@jhyle just ask @karato for more time

**Comment by jhyle** [comment]
@karato takes#548 is in progress, but we need more time

**Comment by karato** [comment]
> @karato takes#548 is in progress, but we need more time

@jhyle of course, take your time

**Comment by jhyle** [comment]
@karato Bug is fixed in Takes - should I wait for a release and then set the version number of Takes in the pom.xml?

**Comment by karato** [comment]
> @karato Bug is fixed in Takes - should I wait for a release and then set the version number of Takes in the pom.xml?

@jhyle I guess so, you better ask project architect (@dmzaytsev)

**Comment by dmzaytsev** [comment]
@jhyle yes, ask for a new release in Takes and then upgrade Netbout to the new release

**Comment by jhyle** [comment]
@dmzaytsev How can I do this?

**Comment by dmzaytsev** [comment]
@jhyle like this https://github.com/yegor256/takes/issues/548#issuecomment-182292072
so please wait until the fix will be released
and then change Takes version in `pom.xml`
