### ISSUE TITLE
Internal Application Error when providing 'since' parameter without value

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#904]
To reproduce just open http://www.netbout.com/?since

![screenshot from 2015-12-28 23 40 10](https://cloud.githubusercontent.com/assets/5467276/12026649/60a79ad4-adbc-11e5-85da-fa93f92ba34e.png)

Stacktrace:
```
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:453)
	at java.lang.Long.parseLong(Long.java:483)
	at com.netbout.rest.TkInbox.bouts(TkInbox.java:103)
	at com.netbout.rest.TkInbox.act(TkInbox.java:77)
	at org.takes.facets.ret.TkReturn.act(TkReturn.java:97)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at com.netbout.rest.FkRegistered$1.route(FkRegistered.java:70)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:80)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:50)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:62)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:106)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

I would expect user-friendly error message instead.

**Comment by karato** [comment]
@dmzaytsev please dispatch this issue

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@mkordas I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@mkordas thanks for reporting! I topped your account for 15 mins, transaction 568a92089d6a2550f50003f1

**Comment by exper0** [comment]
@dmzaytsev ready to fix it

**Comment by dmzaytsev** [comment]
@karato assign @exper0 please

**Comment by karato** [comment]
> @karato assign @exper0 please

@dmzaytsev OK @exper0 please go ahead, this task is yours

**Comment by exper0** [comment]
@mkordas fix for this issue is merged in #956, please close the ticket.

**Comment by mkordas** [comment]
@exper0 thx

**Comment by karato** [comment]
@elenavolokhova please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thank you, good quality is always good ;)

**Comment by karato** [comment]
@exper0 just added 10 mins to @elenavolokhova (for QA), payment ID is `75286572`

Much obliged! I have added **45 mins** to your account in payment "AP-1MG02599J9900842E", 43 hours and 27 mins spent

the bonus for fast delivery (m=2607)

+45 to your rating, your total score is [+526](http://www.netbout.com/b/36185?open=rating)
