### ISSUE TITLE
Skipping tests (-Dmaven.test.skip=true) fails the build

### ISSUE THREAD

**Issue by exper0** [yegor256/netbout#919]
Running maven build without tests fails the build with following error:

java.lang.reflect.InvocationTargetException 
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.lang.reflect.Method.invoke(Method.java:606) 
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293) 
	at java.lang.Thread.run(Thread.java:745) 
Caused by: java.lang.NumberFormatException: For input string: "${smtp.port}" 
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:481)
	at java.lang.Integer.parseInt(Integer.java:527) 
	at com.netbout.Launch.postman(Launch.java:78) 
	at com.netbout.Launch.main(Launch.java:62)

**Comment by exper0** [comment]
not a bug, forgot to set `-DskipTests=true`
