### ISSUE TITLE
Internal Application Error on access to close bout

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#931]
Url accessed: http://www.netbout.com/b/36337
Visible in both Chrome and FF

```
ava.util.NoSuchElementException: no more items in the frame, position=-1
    at com.jcabi.dynamo.AwsIterator.next_aroundBody2(AwsIterator.java:162)
    at com.jcabi.dynamo.AwsIterator$AjcClosure3.run(AwsIterator.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
    at com.jcabi.dynamo.AwsIterator.next(AwsIterator.java:160)
    at com.jcabi.dynamo.AwsIterator.next(AwsIterator.java:62)
    at com.jcabi.dynamo.retry.ReIterator.next_aroundBody4(ReIterator.java:78)
    at com.jcabi.dynamo.retry.ReIterator$AjcClosure5.run(ReIterator.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
    at com.jcabi.dynamo.retry.ReIterator.next_aroundBody6(ReIterator.java:78)
    at com.jcabi.dynamo.retry.ReIterator$AjcClosure7.run(ReIterator.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:82)
    at com.jcabi.dynamo.retry.ReIterator.next(ReIterator.java:78)
    at com.netbout.dynamo.DyMessages.unread_aroundBody2(DyMessages.java:196)
    at com.netbout.dynamo.DyMessages$AjcClosure3.run(DyMessages.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
    at com.netbout.dynamo.DyMessages.unread(DyMessages.java:196)
    at com.netbout.cached.CdMessages$Flag.unread_aroundBody0(CdMessages.java:145)
    at com.netbout.cached.CdMessages$Flag$AjcClosure1.run(CdMessages.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:302)
    at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:147)
    at com.netbout.cached.CdMessages$Flag.unread(CdMessages.java:145)
    at com.netbout.cached.CdMessages.unread_aroundBody2(CdMessages.java:83)
    at com.netbout.cached.CdMessages$AjcClosure3.run(CdMessages.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
    at com.netbout.cached.CdMessages.unread(CdMessages.java:83)
    at com.netbout.email.EmMessages.unread_aroundBody2(EmMessages.java:127)
    at com.netbout.email.EmMessages$AjcClosure3.run(EmMessages.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
    at com.netbout.email.EmMessages.unread(EmMessages.java:127)
    at com.netbout.rest.bout.TkIndex.act(TkIndex.java:82)
    at com.netbout.rest.bout.FkBout$3.act(FkBout.java:111)
    at com.netbout.rest.bout.FkBout$2.act(FkBout.java:89)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
    at com.netbout.rest.bout.FkBout.route(FkBout.java:81)
    at com.netbout.rest.bout.FkBout.access$000(FkBout.java:52)
    at com.netbout.rest.bout.FkBout$1.route(FkBout.java:65)
    at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
    at org.takes.facets.fork.TkFork.act(TkFork.java:101)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
    at org.takes.facets.fork.TkFork.act(TkFork.java:101)
    at com.netbout.rest.FkRegistered$1.route(FkRegistered.java:70)
    at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
    at org.takes.facets.fork.TkFork.act(TkFork.java:101)
    at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
    at org.takes.facets.fork.TkFork.act(TkFork.java:101)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.forward.TkForward.act(TkForward.java:68)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:80)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:50)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:62)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.flash.TkFlash.act(TkFlash.java:106)
    at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.http.BkBasic.print(BkBasic.java:99)
    at org.takes.http.BkBasic.accept(BkBasic.java:77)
    at org.takes.http.BkSafe.accept(BkSafe.java:58)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
    at org.takes.http.BkParallel$1.run(BkParallel.java:97)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by dmzaytsev** [comment]
@longtimeago I have no access to that bout
how is it different from others?

**Comment by longtimeago** [comment]
@dmzaytsev I think it was in progress of deletion.
It's a bout, which was created to interview a canditate.
Right now I'm also don't have an access to it - redirected to the main page.

**Comment by dmzaytsev** [comment]
@yegor256 how implemented the deletion of bouts after an interview? 
Bouts never  deleted in Netbout as I know
Maybe some external process can do that?

**Comment by dmzaytsev** [comment]
@longtimeago it seems the ticket should be closed
I have no idea how to reproduce it

**Comment by longtimeago** [comment]
@dmzaytsev well ... OK, will post another one in case this situation appears again. Thanks

**Comment by longtimeago** [comment]
@dmzaytsev it appears again for http://www.netbout.com/b/36618
![screenshot from 2016-02-16 23 50 02](https://cloud.githubusercontent.com/assets/1388994/13092384/53235538-d508-11e5-83e7-7d13d45fb5fa.png)

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@longtimeago milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev no problem, I will try to find somebody else

**Comment by karato** [comment]
@longtimeago many thanks for the bug report, I added 15 mins to your acc, transaction `78550839`
