### ISSUE TITLE
Internal Application Error: EncryptionOperationNotPossibleException

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#932]
To reproduce just open page http://www.netbout.com/emverify/x and see:

![image](https://cloud.githubusercontent.com/assets/5467276/12367757/083a11ce-bbe5-11e5-8321-1fdab498b53f.png)

Stacktrace:
```
org.jasypt.exceptions.EncryptionOperationNotPossibleException
	at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.decrypt(StandardPBEByteEncryptor.java:974)
	at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.decrypt(StandardPBEStringEncryptor.java:725)
	at com.netbout.rest.TkEmVerify.act(TkEmVerify.java:87)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:80)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:50)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:62)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:100)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable$BkThreads.accept(BkTimeable.java:95)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

I'd expect instead user-friendly information that email verification link is invalid.

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@mkordas I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@mkordas thanks for the report, I topped your acc for 15 mins, payment ID `569d2bbb0f5de046ec0003f1`

**Comment by kujtimiihoxha** [comment]
@dmzaytsev Please assign this task to me.

**Comment by dmzaytsev** [comment]
@karato assign @kujtimiihoxha please

**Comment by karato** [comment]
> @karato assign @kujtimiihoxha please

@dmzaytsev OK @kujtimiihoxha please start, the task is yours

**Comment by kujtimiihoxha** [comment]
@mkordas the issue is solved.
This is how it looks now.
![verify link](https://cloud.githubusercontent.com/assets/14311743/12516521/31e8f7e4-c12e-11e5-82c8-f1476185526a.png)

**Comment by mkordas** [comment]
@kujtimiihoxha from [QA policy](http://at.teamed.io/qa.html):
> Some of ticket messages must mention all pull requests where the problem was actually fixed.

**Comment by kujtimiihoxha** [comment]
@mkordas I updated the comment.

**Comment by mkordas** [comment]
@kujtimiihoxha thanks!

**Comment by karato** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks a lot

**Comment by karato** [comment]
@kujtimiihoxha just added 10 mins to @ypshenychka (for QA), payment ID is `75307235`. Much appreciated! **30 mins** was added to your account, payment ID `AP-71043466A40828814`, time spent is 81 hours and 1 min. +30 to your rating, your total score is [+180](http://www.netbout.com/b/36323?open=rating)
