### ISSUE TITLE
Internal Application Error Version: 2.22

### ISSUE THREAD

**Issue by michaelben** [yegor256/netbout#933]
com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/OAuth/access_token/text()' not found in '\n\n  <..162..#bad-verification-code\n': Index (0) is out of bounds (size=0)
    at com.jcabi.xml.ListWrapper.get(ListWrapper.java:153)
    at org.takes.facets.auth.social.PsGithub.token(PsGithub.java:156)
    at org.takes.facets.auth.social.PsGithub.enter(PsGithub.java:115)
    at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:108)
    at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
    at com.netbout.rest.PsTwice.enter(PsTwice.java:70)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:86)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.forward.TkForward.act(TkForward.java:68)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:80)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:50)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:62)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.flash.TkFlash.act(TkFlash.java:106)
    at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.http.BkBasic.print(BkBasic.java:99)
    at org.takes.http.BkBasic.accept(BkBasic.java:77)
    at org.takes.http.BkSafe.accept(BkSafe.java:58)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
    at org.takes.http.BkParallel$1.run(BkParallel.java:97)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by dmzaytsev** [comment]
@michaelben how  can I reproduce it?

**Comment by michaelben** [comment]
@dmzaytsev This is error when I was trying to register netbout. The error page suggested me to report here. When I reloaded, the error was gone.

**Comment by dmzaytsev** [comment]
@michaelben thanks for reporting
I guess it's a temporary issue 
but we should catch it and display a friendly error message

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@michaelben since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev thanks, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I'll try to find someone else for this task

**Comment by karato** [comment]
@michaelben thanks for the report, I topped your acc for 15 mins, payment ID `AP-8P1054959A3593438`
