### ISSUE TITLE
Cannot access to a netbout

### ISSUE THREAD

**Issue by essobedo** [yegor256/netbout#987]
Hi,

When I tried to access to http://www.netbout.com/b/36421, I get an Internal Application Error with the following stacktrace:
`java.lang.IndexOutOfBoundsException: No group 3
	at java.util.regex.Matcher.start(Matcher.java:374)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:831)
	at com.netbout.rest.MarkdownTxtmark.makeLineBreak(MarkdownTxtmark.java:98)
	at com.netbout.rest.MarkdownTxtmark.html(MarkdownTxtmark.java:63)
	at com.netbout.rest.Markdown$Default.html(Markdown.java:66)
	at com.netbout.rest.bout.XeMessage.make(XeMessage.java:75)
	at com.netbout.rest.bout.XeMessage.(XeMessage.java:63)
	at com.netbout.rest.bout.TkIndex$3.transform(TkIndex.java:138)
	at com.netbout.rest.bout.TkIndex$3.transform(TkIndex.java:134)
	at org.takes.rs.xe.XeTransform$1.next(XeTransform.java:100)
	at org.takes.rs.xe.XeTransform$1.next(XeTransform.java:92)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:62)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:73)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:73)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:73)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.RsXembly.render(RsXembly.java:111)
	at org.takes.rs.xe.RsXembly.access$000(RsXembly.java:59)
	at org.takes.rs.xe.RsXembly$1.body(RsXembly.java:96)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithoutHeader$1.body(RsWithoutHeader.java:75)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrettyXML.make(RsPrettyXML.java:104)
	at org.takes.rs.RsPrettyXML.head(RsPrettyXML.java:88)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.rs.RsWithCookie.previousValue(RsWithCookie.java:168)
	at org.takes.rs.RsWithCookie.access$100(RsWithCookie.java:63)
	at org.takes.rs.RsWithCookie$1.head(RsWithCookie.java:118)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:115)
	at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:134)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:159)
	at org.takes.rs.RsPrint.print(RsPrint.java:113)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable$BkThreads.accept(BkTimeable.java:95)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by essobedo** [comment]
Duplicate Issue

**Comment by dmzaytsev** [comment]
@essobedo do you remember the latest entered text into the bout?

**Comment by essobedo** [comment]
@dmzaytsev According to my emails, it should be something like "Nicolas FILOTTO, I added you to a new campus project: rultor"

**Comment by dmzaytsev** [comment]
@essobedo is there another messages before?

**Comment by essobedo** [comment]
@dmzaytsev Just before I have "Nicolas FILOTTO, I added you to a new campus project: takes" which is very similar to the previous message. Maybe @alice wrote another message that caused the bout to be unstable for which no email notification has been sent.

**Comment by dmzaytsev** [comment]
@essobedo maybe... I can't reproduce it yet
thanks for your help

**Comment by essobedo** [comment]
@dmzaytsev Do you mean that you can access to this particular bout?

**Comment by dmzaytsev** [comment]
@essobedo No, I can't

I mean I can't reproduce the bug in another bout

**Comment by dmzaytsev** [comment]
@essobedo could you try to open your bout?

**Comment by essobedo** [comment]
@dmzaytsev It works perfectly now thank you very much

**Comment by dmzaytsev** [comment]
@essobedo Please share latest messages from the bout  if possible

**Comment by essobedo** [comment]
@dmzaytsev it was "Nicolas FILOTTO, I added you to a new campus project: rultor"

**Comment by dmzaytsev** [comment]
@essobedo hmm, I have no idea why it happens

**Comment by essobedo** [comment]
@dmzaytsev Apart the messages above, the only thing that is new in the bout since the last time I could access it, are the "tabs" agenda earnings leaders rating speed team, I don't know if it helps but I wanted to mention that just in case it could help.

**Comment by dmzaytsev** [comment]
@essobedo I think these tabs not relate to the issue
we will try to look into the logs
thanks!
