### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal group reference

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#991]
Another problem in production, a very annoying and urgent one:

```
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:808)
	at com.netbout.rest.MarkdownTxtmark.makeLineBreak(MarkdownTxtmark.java:100)
	at com.netbout.rest.MarkdownTxtmark.html(MarkdownTxtmark.java:64)
	at com.netbout.rest.Markdown$Default.html(Markdown.java:66)
	at com.netbout.rest.bout.XeMessage.make(XeMessage.java:75)
	at com.netbout.rest.bout.XeMessage.<init>(XeMessage.java:63)
	at com.netbout.rest.bout.TkIndex$3.transform(TkIndex.java:138)
	at com.netbout.rest.bout.TkIndex$3.transform(TkIndex.java:134)
	at org.takes.rs.xe.XeTransform$1.next(XeTransform.java:100)
	at org.takes.rs.xe.XeTransform$1.next(XeTransform.java:92)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:62)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:73)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
```

**Comment by dmzaytsev** [comment]
@yegor256 will be fixed soon
PR #990 waiting for review

**Comment by dmzaytsev** [comment]
@yegor256 I just released the fix, please check

**Comment by yegor256** [comment]
@dmzaytsev works now, thanks
